/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTokenRequest,
  EditTokenRequest,
  OpenShockProblem,
  ProblemDetails,
  ReportTokensRequest,
  TokenCreatedResponse,
  TokenResponse,
} from '../models/index';
import {
    CreateTokenRequestFromJSON,
    CreateTokenRequestToJSON,
    EditTokenRequestFromJSON,
    EditTokenRequestToJSON,
    OpenShockProblemFromJSON,
    OpenShockProblemToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ReportTokensRequestFromJSON,
    ReportTokensRequestToJSON,
    TokenCreatedResponseFromJSON,
    TokenCreatedResponseToJSON,
    TokenResponseFromJSON,
    TokenResponseToJSON,
} from '../models/index';

export interface TokenDeleteDeleteTokenRequest {
    tokenId: string;
}

export interface TokensCreateTokenRequest {
    createTokenRequest?: CreateTokenRequest;
}

export interface TokensEditTokenRequest {
    tokenId: string;
    editTokenRequest?: EditTokenRequest;
}

export interface TokensGetTokenByIdRequest {
    tokenId: string;
}

export interface TokensReportTokensRequest {
    reportTokensRequest?: ReportTokensRequest;
}

/**
 * APITokensApi - interface
 * 
 * @export
 * @interface APITokensApiInterface
 */
export interface APITokensApiInterface {
    /**
     * Creates request options for tokenDeleteDeleteToken without sending the request
     * @param {string} tokenId 
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokenDeleteDeleteTokenRequestOpts(requestParameters: TokenDeleteDeleteTokenRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Revoke a token
     * @param {string} tokenId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokenDeleteDeleteTokenRaw(requestParameters: TokenDeleteDeleteTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Revoke a token
     */
    tokenDeleteDeleteToken(tokenId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for tokensCreateToken without sending the request
     * @param {CreateTokenRequest} [createTokenRequest] 
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensCreateTokenRequestOpts(requestParameters: TokensCreateTokenRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a new token
     * @param {CreateTokenRequest} [createTokenRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensCreateTokenRaw(requestParameters: TokensCreateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenCreatedResponse>>;

    /**
     * Create a new token
     */
    tokensCreateToken(createTokenRequest?: CreateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenCreatedResponse>;

    /**
     * Creates request options for tokensEditToken without sending the request
     * @param {string} tokenId 
     * @param {EditTokenRequest} [editTokenRequest] 
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensEditTokenRequestOpts(requestParameters: TokensEditTokenRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Edit a token
     * @param {string} tokenId 
     * @param {EditTokenRequest} [editTokenRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensEditTokenRaw(requestParameters: TokensEditTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Edit a token
     */
    tokensEditToken(tokenId: string, editTokenRequest?: EditTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for tokensGetTokenById without sending the request
     * @param {string} tokenId 
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensGetTokenByIdRequestOpts(requestParameters: TokensGetTokenByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a token by id
     * @param {string} tokenId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensGetTokenByIdRaw(requestParameters: TokensGetTokenByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>>;

    /**
     * Get a token by id
     */
    tokensGetTokenById(tokenId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse>;

    /**
     * Creates request options for tokensListTokens without sending the request
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensListTokensRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List all tokens for the current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensListTokensRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TokenResponse>>>;

    /**
     * List all tokens for the current user
     */
    tokensListTokens(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TokenResponse>>;

    /**
     * Creates request options for tokensReportTokens without sending the request
     * @param {ReportTokensRequest} [reportTokensRequest] 
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensReportTokensRequestOpts(requestParameters: TokensReportTokensRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Endpoint to delete potentially compromised api tokens
     * @param {ReportTokensRequest} [reportTokensRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensReportTokensRaw(requestParameters: TokensReportTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Endpoint to delete potentially compromised api tokens
     */
    tokensReportTokens(reportTokensRequest?: ReportTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for tokensSelfGetSelfToken without sending the request
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensSelfGetSelfTokenRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Gets information about the current token used to access this endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APITokensApiInterface
     */
    tokensSelfGetSelfTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>>;

    /**
     * Gets information about the current token used to access this endpoint
     */
    tokensSelfGetSelfToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse>;

}

/**
 * 
 */
export class APITokensApi extends runtime.BaseAPI implements APITokensApiInterface {

    /**
     * Creates request options for tokenDeleteDeleteToken without sending the request
     */
    async tokenDeleteDeleteTokenRequestOpts(requestParameters: TokenDeleteDeleteTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tokenId'] == null) {
            throw new runtime.RequiredError(
                'tokenId',
                'Required parameter "tokenId" was null or undefined when calling tokenDeleteDeleteToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["OpenShockToken"] = await this.configuration.apiKey("OpenShockToken"); // ApiToken authentication
        }


        let urlPath = `/1/tokens/{tokenId}`;
        urlPath = urlPath.replace(`{${"tokenId"}}`, encodeURIComponent(String(requestParameters['tokenId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke a token
     */
    async tokenDeleteDeleteTokenRaw(requestParameters: TokenDeleteDeleteTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.tokenDeleteDeleteTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke a token
     */
    async tokenDeleteDeleteToken(tokenId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tokenDeleteDeleteTokenRaw({ tokenId: tokenId }, initOverrides);
    }

    /**
     * Creates request options for tokensCreateToken without sending the request
     */
    async tokensCreateTokenRequestOpts(requestParameters: TokensCreateTokenRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/1/tokens`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTokenRequestToJSON(requestParameters['createTokenRequest']),
        };
    }

    /**
     * Create a new token
     */
    async tokensCreateTokenRaw(requestParameters: TokensCreateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenCreatedResponse>> {
        const requestOptions = await this.tokensCreateTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenCreatedResponseFromJSON(jsonValue));
    }

    /**
     * Create a new token
     */
    async tokensCreateToken(createTokenRequest?: CreateTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenCreatedResponse> {
        const response = await this.tokensCreateTokenRaw({ createTokenRequest: createTokenRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tokensEditToken without sending the request
     */
    async tokensEditTokenRequestOpts(requestParameters: TokensEditTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tokenId'] == null) {
            throw new runtime.RequiredError(
                'tokenId',
                'Required parameter "tokenId" was null or undefined when calling tokensEditToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/1/tokens/{tokenId}`;
        urlPath = urlPath.replace(`{${"tokenId"}}`, encodeURIComponent(String(requestParameters['tokenId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EditTokenRequestToJSON(requestParameters['editTokenRequest']),
        };
    }

    /**
     * Edit a token
     */
    async tokensEditTokenRaw(requestParameters: TokensEditTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.tokensEditTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Edit a token
     */
    async tokensEditToken(tokenId: string, editTokenRequest?: EditTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tokensEditTokenRaw({ tokenId: tokenId, editTokenRequest: editTokenRequest }, initOverrides);
    }

    /**
     * Creates request options for tokensGetTokenById without sending the request
     */
    async tokensGetTokenByIdRequestOpts(requestParameters: TokensGetTokenByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tokenId'] == null) {
            throw new runtime.RequiredError(
                'tokenId',
                'Required parameter "tokenId" was null or undefined when calling tokensGetTokenById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/1/tokens/{tokenId}`;
        urlPath = urlPath.replace(`{${"tokenId"}}`, encodeURIComponent(String(requestParameters['tokenId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a token by id
     */
    async tokensGetTokenByIdRaw(requestParameters: TokensGetTokenByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.tokensGetTokenByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Get a token by id
     */
    async tokensGetTokenById(tokenId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.tokensGetTokenByIdRaw({ tokenId: tokenId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tokensListTokens without sending the request
     */
    async tokensListTokensRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/1/tokens`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all tokens for the current user
     */
    async tokensListTokensRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TokenResponse>>> {
        const requestOptions = await this.tokensListTokensRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TokenResponseFromJSON));
    }

    /**
     * List all tokens for the current user
     */
    async tokensListTokens(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TokenResponse>> {
        const response = await this.tokensListTokensRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tokensReportTokens without sending the request
     */
    async tokensReportTokensRequestOpts(requestParameters: TokensReportTokensRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/1/tokens/report`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReportTokensRequestToJSON(requestParameters['reportTokensRequest']),
        };
    }

    /**
     * Endpoint to delete potentially compromised api tokens
     */
    async tokensReportTokensRaw(requestParameters: TokensReportTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.tokensReportTokensRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Endpoint to delete potentially compromised api tokens
     */
    async tokensReportTokens(reportTokensRequest?: ReportTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tokensReportTokensRaw({ reportTokensRequest: reportTokensRequest }, initOverrides);
    }

    /**
     * Creates request options for tokensSelfGetSelfToken without sending the request
     */
    async tokensSelfGetSelfTokenRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["OpenShockToken"] = await this.configuration.apiKey("OpenShockToken"); // ApiToken authentication
        }


        let urlPath = `/1/tokens/self`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets information about the current token used to access this endpoint
     */
    async tokensSelfGetSelfTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.tokensSelfGetSelfTokenRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Gets information about the current token used to access this endpoint
     */
    async tokensSelfGetSelfToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.tokensSelfGetSelfTokenRaw(initOverrides);
        return await response.value();
    }

}
