/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LegacyEmptyResponse,
  OpenShockProblem,
} from '../models/index';
import {
    LegacyEmptyResponseFromJSON,
    LegacyEmptyResponseToJSON,
    OpenShockProblemFromJSON,
    OpenShockProblemToJSON,
} from '../models/index';

export interface SharesDeleteShareCodeRequest {
    shareCodeId: string;
}

export interface SharesLinkShareCodeRequest {
    shareCodeId: string;
}

/**
 * ShockerSharesApi - interface
 * 
 * @export
 * @interface ShockerSharesApiInterface
 */
export interface ShockerSharesApiInterface {
    /**
     * Creates request options for sharesDeleteShareCode without sending the request
     * @param {string} shareCodeId 
     * @throws {RequiredError}
     * @memberof ShockerSharesApiInterface
     */
    sharesDeleteShareCodeRequestOpts(requestParameters: SharesDeleteShareCodeRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete a share code
     * @param {string} shareCodeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShockerSharesApiInterface
     */
    sharesDeleteShareCodeRaw(requestParameters: SharesDeleteShareCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegacyEmptyResponse>>;

    /**
     * Delete a share code
     */
    sharesDeleteShareCode(shareCodeId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegacyEmptyResponse>;

    /**
     * Creates request options for sharesLinkShareCode without sending the request
     * @param {string} shareCodeId 
     * @throws {RequiredError}
     * @memberof ShockerSharesApiInterface
     */
    sharesLinkShareCodeRequestOpts(requestParameters: SharesLinkShareCodeRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Link a share code to your account
     * @param {string} shareCodeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShockerSharesApiInterface
     */
    sharesLinkShareCodeRaw(requestParameters: SharesLinkShareCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegacyEmptyResponse>>;

    /**
     * Link a share code to your account
     */
    sharesLinkShareCode(shareCodeId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegacyEmptyResponse>;

}

/**
 * 
 */
export class ShockerSharesApi extends runtime.BaseAPI implements ShockerSharesApiInterface {

    /**
     * Creates request options for sharesDeleteShareCode without sending the request
     */
    async sharesDeleteShareCodeRequestOpts(requestParameters: SharesDeleteShareCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['shareCodeId'] == null) {
            throw new runtime.RequiredError(
                'shareCodeId',
                'Required parameter "shareCodeId" was null or undefined when calling sharesDeleteShareCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/1/shares/code/{shareCodeId}`;
        urlPath = urlPath.replace(`{${"shareCodeId"}}`, encodeURIComponent(String(requestParameters['shareCodeId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a share code
     */
    async sharesDeleteShareCodeRaw(requestParameters: SharesDeleteShareCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegacyEmptyResponse>> {
        const requestOptions = await this.sharesDeleteShareCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegacyEmptyResponseFromJSON(jsonValue));
    }

    /**
     * Delete a share code
     */
    async sharesDeleteShareCode(shareCodeId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegacyEmptyResponse> {
        const response = await this.sharesDeleteShareCodeRaw({ shareCodeId: shareCodeId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sharesLinkShareCode without sending the request
     */
    async sharesLinkShareCodeRequestOpts(requestParameters: SharesLinkShareCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['shareCodeId'] == null) {
            throw new runtime.RequiredError(
                'shareCodeId',
                'Required parameter "shareCodeId" was null or undefined when calling sharesLinkShareCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/1/shares/code/{shareCodeId}`;
        urlPath = urlPath.replace(`{${"shareCodeId"}}`, encodeURIComponent(String(requestParameters['shareCodeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Link a share code to your account
     */
    async sharesLinkShareCodeRaw(requestParameters: SharesLinkShareCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegacyEmptyResponse>> {
        const requestOptions = await this.sharesLinkShareCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegacyEmptyResponseFromJSON(jsonValue));
    }

    /**
     * Link a share code to your account
     */
    async sharesLinkShareCode(shareCodeId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegacyEmptyResponse> {
        const response = await this.sharesLinkShareCodeRaw({ shareCodeId: shareCodeId }, initOverrides);
        return await response.value();
    }

}
