allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
blockExoticSubdeps: true
minimumReleaseAge: 4320 # 3 days

minimumReleaseAgeExclude:
  - ws@8.20.1
  - esbuild@0.28.1
  - js-yaml@4.1.2
  - ts-deepmerge@8.0.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
overrides:
  brace-expansion@<5.0.5: '>=5.0.5'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  js-yaml@<4.1.1: '>=4.1.1'
  js-yaml@<=4.1.1: ^4.1.2
  ts-deepmerge@<8.0.0: ^8.0.0
  undici@>=7.0.0 <7.24.0: '>=7.24.0'
  uuid@<14.0.0: '>=14.0.0'
  ws@>=8.0.0 <8.20.1: ^8.20.1

patchedDependencies:
  '@microsoft/signalr@10.0.0': patches/signalr.patch

#trustPolicy: no-downgrade
