/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchTypeEnum } from './MatchTypeEnum';
import {
    MatchTypeEnumFromJSON,
    MatchTypeEnumFromJSONTyped,
    MatchTypeEnumToJSON,
    MatchTypeEnumToJSONTyped,
} from './MatchTypeEnum';

/**
 * 
 * @export
 * @interface AddUsernameBlacklistDto
 */
export interface AddUsernameBlacklistDto {
    /**
     * 
     * @type {string}
     * @memberof AddUsernameBlacklistDto
     */
    value: string;
    /**
     * 
     * @type {MatchTypeEnum}
     * @memberof AddUsernameBlacklistDto
     */
    matchType: MatchTypeEnum;
}



/**
 * Check if a given object implements the AddUsernameBlacklistDto interface.
 */
export function instanceOfAddUsernameBlacklistDto(value: object): value is AddUsernameBlacklistDto {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('matchType' in value) || value['matchType'] === undefined) return false;
    return true;
}

export function AddUsernameBlacklistDtoFromJSON(json: any): AddUsernameBlacklistDto {
    return AddUsernameBlacklistDtoFromJSONTyped(json, false);
}

export function AddUsernameBlacklistDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUsernameBlacklistDto {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'matchType': MatchTypeEnumFromJSON(json['matchType']),
    };
}

export function AddUsernameBlacklistDtoToJSON(json: any): AddUsernameBlacklistDto {
    return AddUsernameBlacklistDtoToJSONTyped(json, false);
}

export function AddUsernameBlacklistDtoToJSONTyped(value?: AddUsernameBlacklistDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'matchType': MatchTypeEnumToJSON(value['matchType']),
    };
}

