/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddWebhookDto
 */
export interface AddWebhookDto {
    /**
     * 
     * @type {string}
     * @memberof AddWebhookDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddWebhookDto
     */
    url: string;
}

/**
 * Check if a given object implements the AddWebhookDto interface.
 */
export function instanceOfAddWebhookDto(value: object): value is AddWebhookDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function AddWebhookDtoFromJSON(json: any): AddWebhookDto {
    return AddWebhookDtoFromJSONTyped(json, false);
}

export function AddWebhookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddWebhookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
    };
}

export function AddWebhookDtoToJSON(json: any): AddWebhookDto {
    return AddWebhookDtoToJSONTyped(json, false);
}

export function AddWebhookDtoToJSONTyped(value?: AddWebhookDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
    };
}

