/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminOnlineDeviceResponse } from './AdminOnlineDeviceResponse';
import {
    AdminOnlineDeviceResponseFromJSON,
    AdminOnlineDeviceResponseFromJSONTyped,
    AdminOnlineDeviceResponseToJSON,
    AdminOnlineDeviceResponseToJSONTyped,
} from './AdminOnlineDeviceResponse';

/**
 * 
 * @export
 * @interface AdminOnlineDeviceResponseIEnumerableLegacyDataResponse
 */
export interface AdminOnlineDeviceResponseIEnumerableLegacyDataResponse {
    /**
     * 
     * @type {string}
     * @memberof AdminOnlineDeviceResponseIEnumerableLegacyDataResponse
     */
    message: string;
    /**
     * 
     * @type {Array<AdminOnlineDeviceResponse>}
     * @memberof AdminOnlineDeviceResponseIEnumerableLegacyDataResponse
     */
    data: Array<AdminOnlineDeviceResponse> | null;
}

/**
 * Check if a given object implements the AdminOnlineDeviceResponseIEnumerableLegacyDataResponse interface.
 */
export function instanceOfAdminOnlineDeviceResponseIEnumerableLegacyDataResponse(value: object): value is AdminOnlineDeviceResponseIEnumerableLegacyDataResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AdminOnlineDeviceResponseIEnumerableLegacyDataResponseFromJSON(json: any): AdminOnlineDeviceResponseIEnumerableLegacyDataResponse {
    return AdminOnlineDeviceResponseIEnumerableLegacyDataResponseFromJSONTyped(json, false);
}

export function AdminOnlineDeviceResponseIEnumerableLegacyDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOnlineDeviceResponseIEnumerableLegacyDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(AdminOnlineDeviceResponseFromJSON)),
    };
}

export function AdminOnlineDeviceResponseIEnumerableLegacyDataResponseToJSON(json: any): AdminOnlineDeviceResponseIEnumerableLegacyDataResponse {
    return AdminOnlineDeviceResponseIEnumerableLegacyDataResponseToJSONTyped(json, false);
}

export function AdminOnlineDeviceResponseIEnumerableLegacyDataResponseToJSONTyped(value?: AdminOnlineDeviceResponseIEnumerableLegacyDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(AdminOnlineDeviceResponseToJSON)),
    };
}

