/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControlLogSenderLight
 */
export interface ControlLogSenderLight {
    /**
     * 
     * @type {string}
     * @memberof ControlLogSenderLight
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ControlLogSenderLight
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ControlLogSenderLight
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof ControlLogSenderLight
     */
    customName?: string;
}

/**
 * Check if a given object implements the ControlLogSenderLight interface.
 */
export function instanceOfControlLogSenderLight(value: object): boolean {
    return true;
}

export function ControlLogSenderLightFromJSON(json: any): ControlLogSenderLight {
    return ControlLogSenderLightFromJSONTyped(json, false);
}

export function ControlLogSenderLightFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControlLogSenderLight {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'customName': json['customName'] == null ? undefined : json['customName'],
    };
}

export function ControlLogSenderLightToJSON(value?: ControlLogSenderLight | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'image': value['image'],
        'customName': value['customName'],
    };
}

