/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PermissionType } from './PermissionType';
import {
    PermissionTypeFromJSON,
    PermissionTypeFromJSONTyped,
    PermissionTypeToJSON,
} from './PermissionType';

/**
 * 
 * @export
 * @interface CreateTokenRequest
 */
export interface CreateTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTokenRequest
     */
    name?: string | null;
    /**
     * 
     * @type {Array<PermissionType>}
     * @memberof CreateTokenRequest
     */
    permissions?: Array<PermissionType> | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateTokenRequest
     */
    validUntil?: Date | null;
}

/**
 * Check if a given object implements the CreateTokenRequest interface.
 */
export function instanceOfCreateTokenRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateTokenRequestFromJSON(json: any): CreateTokenRequest {
    return CreateTokenRequestFromJSONTyped(json, false);
}

export function CreateTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'permissions': !exists(json, 'permissions') ? undefined : (json['permissions'] === null ? null : (json['permissions'] as Array<any>).map(PermissionTypeFromJSON)),
        'validUntil': !exists(json, 'validUntil') ? undefined : (json['validUntil'] === null ? null : new Date(json['validUntil'])),
    };
}

export function CreateTokenRequestToJSON(value?: CreateTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'permissions': value.permissions === undefined ? undefined : (value.permissions === null ? null : (value.permissions as Array<any>).map(PermissionTypeToJSON)),
        'validUntil': value.validUntil === undefined ? undefined : (value.validUntil === null ? null : value.validUntil.toISOString().substring(0,10)),
    };
}

