/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceSelfResponse } from './DeviceSelfResponse';
import {
    DeviceSelfResponseFromJSON,
    DeviceSelfResponseFromJSONTyped,
    DeviceSelfResponseToJSON,
} from './DeviceSelfResponse';

/**
 * 
 * @export
 * @interface DeviceSelfResponseBaseResponse
 */
export interface DeviceSelfResponseBaseResponse {
    /**
     * 
     * @type {string}
     * @memberof DeviceSelfResponseBaseResponse
     */
    message?: string | null;
    /**
     * 
     * @type {DeviceSelfResponse}
     * @memberof DeviceSelfResponseBaseResponse
     */
    data?: DeviceSelfResponse;
}

/**
 * Check if a given object implements the DeviceSelfResponseBaseResponse interface.
 */
export function instanceOfDeviceSelfResponseBaseResponse(value: object): value is DeviceSelfResponseBaseResponse {
    return true;
}

export function DeviceSelfResponseBaseResponseFromJSON(json: any): DeviceSelfResponseBaseResponse {
    return DeviceSelfResponseBaseResponseFromJSONTyped(json, false);
}

export function DeviceSelfResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceSelfResponseBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : DeviceSelfResponseFromJSON(json['data']),
    };
}

export function DeviceSelfResponseBaseResponseToJSON(value?: DeviceSelfResponseBaseResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'data': DeviceSelfResponseToJSON(value['data']),
    };
}

