/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LcgNodeResponse } from './LcgNodeResponse';
import {
    LcgNodeResponseFromJSON,
    LcgNodeResponseFromJSONTyped,
    LcgNodeResponseToJSON,
    LcgNodeResponseToJSONTyped,
} from './LcgNodeResponse';

/**
 * 
 * @export
 * @interface LcgNodeResponseBaseResponse
 */
export interface LcgNodeResponseBaseResponse {
    /**
     * 
     * @type {string}
     * @memberof LcgNodeResponseBaseResponse
     */
    message?: string | null;
    /**
     * 
     * @type {LcgNodeResponse}
     * @memberof LcgNodeResponseBaseResponse
     */
    data?: LcgNodeResponse;
}

/**
 * Check if a given object implements the LcgNodeResponseBaseResponse interface.
 */
export function instanceOfLcgNodeResponseBaseResponse(value: object): value is LcgNodeResponseBaseResponse {
    return true;
}

export function LcgNodeResponseBaseResponseFromJSON(json: any): LcgNodeResponseBaseResponse {
    return LcgNodeResponseBaseResponseFromJSONTyped(json, false);
}

export function LcgNodeResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LcgNodeResponseBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : LcgNodeResponseFromJSON(json['data']),
    };
}

  export function LcgNodeResponseBaseResponseToJSON(json: any): LcgNodeResponseBaseResponse {
      return LcgNodeResponseBaseResponseToJSONTyped(json, false);
  }

  export function LcgNodeResponseBaseResponseToJSONTyped(value?: LcgNodeResponseBaseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': LcgNodeResponseToJSON(value['data']),
    };
}

