/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OwnPublicShareResponse } from './OwnPublicShareResponse';
import {
    OwnPublicShareResponseFromJSON,
    OwnPublicShareResponseFromJSONTyped,
    OwnPublicShareResponseToJSON,
    OwnPublicShareResponseToJSONTyped,
} from './OwnPublicShareResponse';

/**
 * 
 * @export
 * @interface OwnPublicShareResponseArrayLegacyDataResponse
 */
export interface OwnPublicShareResponseArrayLegacyDataResponse {
    /**
     * 
     * @type {string}
     * @memberof OwnPublicShareResponseArrayLegacyDataResponse
     */
    message: string;
    /**
     * 
     * @type {Array<OwnPublicShareResponse>}
     * @memberof OwnPublicShareResponseArrayLegacyDataResponse
     */
    data: Array<OwnPublicShareResponse> | null;
}

/**
 * Check if a given object implements the OwnPublicShareResponseArrayLegacyDataResponse interface.
 */
export function instanceOfOwnPublicShareResponseArrayLegacyDataResponse(value: object): value is OwnPublicShareResponseArrayLegacyDataResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OwnPublicShareResponseArrayLegacyDataResponseFromJSON(json: any): OwnPublicShareResponseArrayLegacyDataResponse {
    return OwnPublicShareResponseArrayLegacyDataResponseFromJSONTyped(json, false);
}

export function OwnPublicShareResponseArrayLegacyDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OwnPublicShareResponseArrayLegacyDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(OwnPublicShareResponseFromJSON)),
    };
}

export function OwnPublicShareResponseArrayLegacyDataResponseToJSON(json: any): OwnPublicShareResponseArrayLegacyDataResponse {
    return OwnPublicShareResponseArrayLegacyDataResponseToJSONTyped(json, false);
}

export function OwnPublicShareResponseArrayLegacyDataResponseToJSONTyped(value?: OwnPublicShareResponseArrayLegacyDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(OwnPublicShareResponseToJSON)),
    };
}

