/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PauseReason } from './PauseReason';
import {
    PauseReasonFromJSON,
    PauseReasonFromJSONTyped,
    PauseReasonToJSON,
} from './PauseReason';

/**
 * 
 * @export
 * @interface PauseReasonBaseResponse
 */
export interface PauseReasonBaseResponse {
    /**
     * 
     * @type {string}
     * @memberof PauseReasonBaseResponse
     */
    message?: string | null;
    /**
     * 
     * @type {PauseReason}
     * @memberof PauseReasonBaseResponse
     */
    data?: PauseReason;
}

/**
 * Check if a given object implements the PauseReasonBaseResponse interface.
 */
export function instanceOfPauseReasonBaseResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PauseReasonBaseResponseFromJSON(json: any): PauseReasonBaseResponse {
    return PauseReasonBaseResponseFromJSONTyped(json, false);
}

export function PauseReasonBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PauseReasonBaseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : PauseReasonFromJSON(json['data']),
    };
}

export function PauseReasonBaseResponseToJSON(value?: PauseReasonBaseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'data': PauseReasonToJSON(value.data),
    };
}

