/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrereleaseIdentifier
 */
export interface PrereleaseIdentifier {
    /**
     * 
     * @type {string}
     * @memberof PrereleaseIdentifier
     */
    value?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PrereleaseIdentifier
     */
    readonly numericValue?: number | null;
}

/**
 * Check if a given object implements the PrereleaseIdentifier interface.
 */
export function instanceOfPrereleaseIdentifier(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PrereleaseIdentifierFromJSON(json: any): PrereleaseIdentifier {
    return PrereleaseIdentifierFromJSONTyped(json, false);
}

export function PrereleaseIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrereleaseIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'numericValue': !exists(json, 'numericValue') ? undefined : json['numericValue'],
    };
}

export function PrereleaseIdentifierToJSON(value?: PrereleaseIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

