/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PublicShareLinkResponse } from './PublicShareLinkResponse';
import {
    PublicShareLinkResponseFromJSON,
    PublicShareLinkResponseFromJSONTyped,
    PublicShareLinkResponseToJSON,
} from './PublicShareLinkResponse';

/**
 * 
 * @export
 * @interface PublicShareLinkResponseBaseResponse
 */
export interface PublicShareLinkResponseBaseResponse {
    /**
     * 
     * @type {string}
     * @memberof PublicShareLinkResponseBaseResponse
     */
    message?: string | null;
    /**
     * 
     * @type {PublicShareLinkResponse}
     * @memberof PublicShareLinkResponseBaseResponse
     */
    data?: PublicShareLinkResponse;
}

/**
 * Check if a given object implements the PublicShareLinkResponseBaseResponse interface.
 */
export function instanceOfPublicShareLinkResponseBaseResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublicShareLinkResponseBaseResponseFromJSON(json: any): PublicShareLinkResponseBaseResponse {
    return PublicShareLinkResponseBaseResponseFromJSONTyped(json, false);
}

export function PublicShareLinkResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicShareLinkResponseBaseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : PublicShareLinkResponseFromJSON(json['data']),
    };
}

export function PublicShareLinkResponseBaseResponseToJSON(value?: PublicShareLinkResponseBaseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'data': PublicShareLinkResponseToJSON(value.data),
    };
}

