/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RootResponse
 */
export interface RootResponse {
    /**
     * 
     * @type {string}
     * @memberof RootResponse
     */
    version?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RootResponse
     */
    commit?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RootResponse
     */
    currentTime?: Date;
}

/**
 * Check if a given object implements the RootResponse interface.
 */
export function instanceOfRootResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RootResponseFromJSON(json: any): RootResponse {
    return RootResponseFromJSONTyped(json, false);
}

export function RootResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'commit': !exists(json, 'commit') ? undefined : json['commit'],
        'currentTime': !exists(json, 'currentTime') ? undefined : (new Date(json['currentTime'])),
    };
}

export function RootResponseToJSON(value?: RootResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'commit': value.commit,
        'currentTime': value.currentTime === undefined ? undefined : (value.currentTime.toISOString()),
    };
}

