/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RootResponse } from './RootResponse';
import {
    RootResponseFromJSON,
    RootResponseFromJSONTyped,
    RootResponseToJSON,
} from './RootResponse';

/**
 * 
 * @export
 * @interface RootResponseBaseResponse
 */
export interface RootResponseBaseResponse {
    /**
     * 
     * @type {string}
     * @memberof RootResponseBaseResponse
     */
    message?: string | null;
    /**
     * 
     * @type {RootResponse}
     * @memberof RootResponseBaseResponse
     */
    data?: RootResponse;
}

/**
 * Check if a given object implements the RootResponseBaseResponse interface.
 */
export function instanceOfRootResponseBaseResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RootResponseBaseResponseFromJSON(json: any): RootResponseBaseResponse {
    return RootResponseBaseResponseFromJSONTyped(json, false);
}

export function RootResponseBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootResponseBaseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : RootResponseFromJSON(json['data']),
    };
}

export function RootResponseBaseResponseToJSON(value?: RootResponseBaseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'data': RootResponseToJSON(value.data),
    };
}

