/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RootResponse
 */
export interface RootResponse {
    /**
     * 
     * @type {string}
     * @memberof RootResponse
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof RootResponse
     */
    commit?: string;
    /**
     * 
     * @type {Date}
     * @memberof RootResponse
     */
    currentTime?: Date;
}

/**
 * Check if a given object implements the RootResponse interface.
 */
export function instanceOfRootResponse(value: object): boolean {
    return true;
}

export function RootResponseFromJSON(json: any): RootResponse {
    return RootResponseFromJSONTyped(json, false);
}

export function RootResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'commit': json['commit'] == null ? undefined : json['commit'],
        'currentTime': json['currentTime'] == null ? undefined : (new Date(json['currentTime'])),
    };
}

export function RootResponseToJSON(value?: RootResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'version': value['version'],
        'commit': value['commit'],
        'currentTime': value['currentTime'] == null ? undefined : ((value['currentTime']).toISOString()),
    };
}

