/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShockerPermissions } from './ShockerPermissions';
import {
    ShockerPermissionsFromJSON,
    ShockerPermissionsFromJSONTyped,
    ShockerPermissionsToJSON,
} from './ShockerPermissions';
import type { ShockerLimits } from './ShockerLimits';
import {
    ShockerLimitsFromJSON,
    ShockerLimitsFromJSONTyped,
    ShockerLimitsToJSON,
} from './ShockerLimits';

/**
 * 
 * @export
 * @interface ShareLinkEditShocker
 */
export interface ShareLinkEditShocker {
    /**
     * 
     * @type {ShockerPermissions}
     * @memberof ShareLinkEditShocker
     */
    permissions: ShockerPermissions;
    /**
     * 
     * @type {ShockerLimits}
     * @memberof ShareLinkEditShocker
     */
    limits: ShockerLimits;
    /**
     * 
     * @type {number}
     * @memberof ShareLinkEditShocker
     */
    cooldown?: number | null;
}

/**
 * Check if a given object implements the ShareLinkEditShocker interface.
 */
export function instanceOfShareLinkEditShocker(value: object): value is ShareLinkEditShocker {
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('limits' in value) || value['limits'] === undefined) return false;
    return true;
}

export function ShareLinkEditShockerFromJSON(json: any): ShareLinkEditShocker {
    return ShareLinkEditShockerFromJSONTyped(json, false);
}

export function ShareLinkEditShockerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareLinkEditShocker {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': ShockerPermissionsFromJSON(json['permissions']),
        'limits': ShockerLimitsFromJSON(json['limits']),
        'cooldown': json['cooldown'] == null ? undefined : json['cooldown'],
    };
}

export function ShareLinkEditShockerToJSON(value?: ShareLinkEditShocker | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'permissions': ShockerPermissionsToJSON(value['permissions']),
        'limits': ShockerLimitsToJSON(value['limits']),
        'cooldown': value['cooldown'],
    };
}

