/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShareInfo } from './ShareInfo';
import {
    ShareInfoFromJSON,
    ShareInfoFromJSONTyped,
    ShareInfoToJSON,
} from './ShareInfo';

/**
 * 
 * @export
 * @interface ShareInfoIEnumerableBaseResponse
 */
export interface ShareInfoIEnumerableBaseResponse {
    /**
     * 
     * @type {string}
     * @memberof ShareInfoIEnumerableBaseResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<ShareInfo>}
     * @memberof ShareInfoIEnumerableBaseResponse
     */
    data?: Array<ShareInfo>;
}

/**
 * Check if a given object implements the ShareInfoIEnumerableBaseResponse interface.
 */
export function instanceOfShareInfoIEnumerableBaseResponse(value: object): value is ShareInfoIEnumerableBaseResponse {
    return true;
}

export function ShareInfoIEnumerableBaseResponseFromJSON(json: any): ShareInfoIEnumerableBaseResponse {
    return ShareInfoIEnumerableBaseResponseFromJSONTyped(json, false);
}

export function ShareInfoIEnumerableBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareInfoIEnumerableBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ShareInfoFromJSON)),
    };
}

export function ShareInfoIEnumerableBaseResponseToJSON(value?: ShareInfoIEnumerableBaseResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ShareInfoToJSON)),
    };
}

