/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShareLinkResponse } from './ShareLinkResponse';
import {
    ShareLinkResponseFromJSON,
    ShareLinkResponseFromJSONTyped,
    ShareLinkResponseToJSON,
    ShareLinkResponseToJSONTyped,
} from './ShareLinkResponse';

/**
 * 
 * @export
 * @interface ShareLinkResponseLegacyDataResponse
 */
export interface ShareLinkResponseLegacyDataResponse {
    /**
     * 
     * @type {string}
     * @memberof ShareLinkResponseLegacyDataResponse
     */
    message: string;
    /**
     * 
     * @type {ShareLinkResponse}
     * @memberof ShareLinkResponseLegacyDataResponse
     */
    data: ShareLinkResponse;
}

/**
 * Check if a given object implements the ShareLinkResponseLegacyDataResponse interface.
 */
export function instanceOfShareLinkResponseLegacyDataResponse(value: object): value is ShareLinkResponseLegacyDataResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ShareLinkResponseLegacyDataResponseFromJSON(json: any): ShareLinkResponseLegacyDataResponse {
    return ShareLinkResponseLegacyDataResponseFromJSONTyped(json, false);
}

export function ShareLinkResponseLegacyDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareLinkResponseLegacyDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': ShareLinkResponseFromJSON(json['data']),
    };
}

export function ShareLinkResponseLegacyDataResponseToJSON(json: any): ShareLinkResponseLegacyDataResponse {
    return ShareLinkResponseLegacyDataResponseToJSONTyped(json, false);
}

export function ShareLinkResponseLegacyDataResponseToJSONTyped(value?: ShareLinkResponseLegacyDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': ShareLinkResponseToJSON(value['data']),
    };
}

