/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShareCodeInfo } from './ShareCodeInfo';
import {
    ShareCodeInfoFromJSON,
    ShareCodeInfoFromJSONTyped,
    ShareCodeInfoToJSON,
    ShareCodeInfoToJSONTyped,
} from './ShareCodeInfo';

/**
 * 
 * @export
 * @interface ShareCodeInfoArrayLegacyDataResponse
 */
export interface ShareCodeInfoArrayLegacyDataResponse {
    /**
     * 
     * @type {string}
     * @memberof ShareCodeInfoArrayLegacyDataResponse
     */
    message: string;
    /**
     * 
     * @type {Array<ShareCodeInfo>}
     * @memberof ShareCodeInfoArrayLegacyDataResponse
     */
    data: Array<ShareCodeInfo> | null;
}

/**
 * Check if a given object implements the ShareCodeInfoArrayLegacyDataResponse interface.
 */
export function instanceOfShareCodeInfoArrayLegacyDataResponse(value: object): value is ShareCodeInfoArrayLegacyDataResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ShareCodeInfoArrayLegacyDataResponseFromJSON(json: any): ShareCodeInfoArrayLegacyDataResponse {
    return ShareCodeInfoArrayLegacyDataResponseFromJSONTyped(json, false);
}

export function ShareCodeInfoArrayLegacyDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareCodeInfoArrayLegacyDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(ShareCodeInfoFromJSON)),
    };
}

export function ShareCodeInfoArrayLegacyDataResponseToJSON(json: any): ShareCodeInfoArrayLegacyDataResponse {
    return ShareCodeInfoArrayLegacyDataResponseToJSONTyped(json, false);
}

export function ShareCodeInfoArrayLegacyDataResponseToJSONTyped(value?: ShareCodeInfoArrayLegacyDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(ShareCodeInfoToJSON)),
    };
}

