/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareCodeInfo
 */
export interface ShareCodeInfo {
    /**
     * 
     * @type {string}
     * @memberof ShareCodeInfo
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ShareCodeInfo
     */
    createdOn?: Date;
}

/**
 * Check if a given object implements the ShareCodeInfo interface.
 */
export function instanceOfShareCodeInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ShareCodeInfoFromJSON(json: any): ShareCodeInfo {
    return ShareCodeInfoFromJSONTyped(json, false);
}

export function ShareCodeInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareCodeInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdOn': !exists(json, 'createdOn') ? undefined : (new Date(json['createdOn'])),
    };
}

export function ShareCodeInfoToJSON(value?: ShareCodeInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdOn': value.createdOn === undefined ? undefined : (value.createdOn.toISOString()),
    };
}

