/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ShockerModelType } from './ShockerModelType';
import {
    ShockerModelTypeFromJSON,
    ShockerModelTypeFromJSONTyped,
    ShockerModelTypeToJSON,
} from './ShockerModelType';

/**
 * 
 * @export
 * @interface ShockerWithDevice
 */
export interface ShockerWithDevice {
    /**
     * 
     * @type {string}
     * @memberof ShockerWithDevice
     */
    device?: string;
    /**
     * 
     * @type {string}
     * @memberof ShockerWithDevice
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ShockerWithDevice
     */
    isPaused?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ShockerWithDevice
     */
    createdOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShockerWithDevice
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ShockerWithDevice
     */
    rfId?: number;
    /**
     * 
     * @type {ShockerModelType}
     * @memberof ShockerWithDevice
     */
    model?: ShockerModelType;
}

/**
 * Check if a given object implements the ShockerWithDevice interface.
 */
export function instanceOfShockerWithDevice(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ShockerWithDeviceFromJSON(json: any): ShockerWithDevice {
    return ShockerWithDeviceFromJSONTyped(json, false);
}

export function ShockerWithDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShockerWithDevice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'device': !exists(json, 'device') ? undefined : json['device'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isPaused': !exists(json, 'isPaused') ? undefined : json['isPaused'],
        'createdOn': !exists(json, 'createdOn') ? undefined : (new Date(json['createdOn'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rfId': !exists(json, 'rfId') ? undefined : json['rfId'],
        'model': !exists(json, 'model') ? undefined : ShockerModelTypeFromJSON(json['model']),
    };
}

export function ShockerWithDeviceToJSON(value?: ShockerWithDevice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'device': value.device,
        'name': value.name,
        'isPaused': value.isPaused,
        'createdOn': value.createdOn === undefined ? undefined : (value.createdOn.toISOString()),
        'id': value.id,
        'rfId': value.rfId,
        'model': ShockerModelTypeToJSON(value.model),
    };
}

