/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenCreatedResponse
 */
export interface TokenCreatedResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenCreatedResponse
     */
    token: string;
}

/**
 * Check if a given object implements the TokenCreatedResponse interface.
 */
export function instanceOfTokenCreatedResponse(value: object): value is TokenCreatedResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function TokenCreatedResponseFromJSON(json: any): TokenCreatedResponse {
    return TokenCreatedResponseFromJSONTyped(json, false);
}

export function TokenCreatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenCreatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

  export function TokenCreatedResponseToJSON(json: any): TokenCreatedResponse {
      return TokenCreatedResponseToJSONTyped(json, false);
  }

  export function TokenCreatedResponseToJSONTyped(value?: TokenCreatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

