/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSelfResponse } from './UserSelfResponse';
import {
    UserSelfResponseFromJSON,
    UserSelfResponseFromJSONTyped,
    UserSelfResponseToJSON,
    UserSelfResponseToJSONTyped,
} from './UserSelfResponse';

/**
 * 
 * @export
 * @interface UserSelfResponseLegacyDataResponse
 */
export interface UserSelfResponseLegacyDataResponse {
    /**
     * 
     * @type {string}
     * @memberof UserSelfResponseLegacyDataResponse
     */
    message: string;
    /**
     * 
     * @type {UserSelfResponse}
     * @memberof UserSelfResponseLegacyDataResponse
     */
    data: UserSelfResponse;
}

/**
 * Check if a given object implements the UserSelfResponseLegacyDataResponse interface.
 */
export function instanceOfUserSelfResponseLegacyDataResponse(value: object): value is UserSelfResponseLegacyDataResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UserSelfResponseLegacyDataResponseFromJSON(json: any): UserSelfResponseLegacyDataResponse {
    return UserSelfResponseLegacyDataResponseFromJSONTyped(json, false);
}

export function UserSelfResponseLegacyDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSelfResponseLegacyDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': UserSelfResponseFromJSON(json['data']),
    };
}

export function UserSelfResponseLegacyDataResponseToJSON(json: any): UserSelfResponseLegacyDataResponse {
    return UserSelfResponseLegacyDataResponseToJSONTyped(json, false);
}

export function UserSelfResponseLegacyDataResponseToJSONTyped(value?: UserSelfResponseLegacyDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': UserSelfResponseToJSON(value['data']),
    };
}

