/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum UsernameAvailability {
    available = 'Available',
    taken = 'Taken',
    invalid = 'Invalid',
    unknownDefaultOpenApi = '11184809'
}


export function instanceOfUsernameAvailability(value: any): boolean {
    for (const key in UsernameAvailability) {
        if (Object.prototype.hasOwnProperty.call(UsernameAvailability, key)) {
            if ((UsernameAvailability as Record<string, UsernameAvailability>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UsernameAvailabilityFromJSON(json: any): UsernameAvailability {
    return UsernameAvailabilityFromJSONTyped(json, false);
}

export function UsernameAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsernameAvailability {
    return json as UsernameAvailability;
}

export function UsernameAvailabilityToJSON(value?: UsernameAvailability | null): any {
    return value as any;
}

