/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LcgNodeResponseV2
 */
export interface LcgNodeResponseV2 {
    /**
     * 
     * @type {string}
     * @memberof LcgNodeResponseV2
     */
    host: string;
    /**
     * 
     * @type {number}
     * @memberof LcgNodeResponseV2
     */
    port: number;
    /**
     * 
     * @type {string}
     * @memberof LcgNodeResponseV2
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof LcgNodeResponseV2
     */
    country: string;
}

/**
 * Check if a given object implements the LcgNodeResponseV2 interface.
 */
export function instanceOfLcgNodeResponseV2(value: object): value is LcgNodeResponseV2 {
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function LcgNodeResponseV2FromJSON(json: any): LcgNodeResponseV2 {
    return LcgNodeResponseV2FromJSONTyped(json, false);
}

export function LcgNodeResponseV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): LcgNodeResponseV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'],
        'port': json['port'],
        'path': json['path'],
        'country': json['country'],
    };
}

export function LcgNodeResponseV2ToJSON(json: any): LcgNodeResponseV2 {
    return LcgNodeResponseV2ToJSONTyped(json, false);
}

export function LcgNodeResponseV2ToJSONTyped(value?: LcgNodeResponseV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
        'port': value['port'],
        'path': value['path'],
        'country': value['country'],
    };
}

