/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LcgResponse
 */
export interface LcgResponse {
    /**
     * 
     * @type {string}
     * @memberof LcgResponse
     */
    gateway?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LcgResponse
     */
    country?: string | null;
}

/**
 * Check if a given object implements the LcgResponse interface.
 */
export function instanceOfLcgResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LcgResponseFromJSON(json: any): LcgResponse {
    return LcgResponseFromJSONTyped(json, false);
}

export function LcgResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LcgResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gateway': !exists(json, 'gateway') ? undefined : json['gateway'],
        'country': !exists(json, 'country') ? undefined : json['country'],
    };
}

export function LcgResponseToJSON(value?: LcgResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gateway': value.gateway,
        'country': value.country,
    };
}

