/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectBaseResponse
 */
export interface ObjectBaseResponse {
    /**
     * 
     * @type {string}
     * @memberof ObjectBaseResponse
     */
    message?: string | null;
    /**
     * 
     * @type {any}
     * @memberof ObjectBaseResponse
     */
    data?: any | null;
}

/**
 * Check if a given object implements the ObjectBaseResponse interface.
 */
export function instanceOfObjectBaseResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ObjectBaseResponseFromJSON(json: any): ObjectBaseResponse {
    return ObjectBaseResponseFromJSONTyped(json, false);
}

export function ObjectBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectBaseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function ObjectBaseResponseToJSON(value?: ObjectBaseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'data': value.data,
    };
}

