/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PauseUserShareShockersRequest
 */
export interface PauseUserShareShockersRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof PauseUserShareShockersRequest
     */
    shockers: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PauseUserShareShockersRequest
     */
    pause: boolean;
}

/**
 * Check if a given object implements the PauseUserShareShockersRequest interface.
 */
export function instanceOfPauseUserShareShockersRequest(value: object): value is PauseUserShareShockersRequest {
    if (!('shockers' in value) || value['shockers'] === undefined) return false;
    if (!('pause' in value) || value['pause'] === undefined) return false;
    return true;
}

export function PauseUserShareShockersRequestFromJSON(json: any): PauseUserShareShockersRequest {
    return PauseUserShareShockersRequestFromJSONTyped(json, false);
}

export function PauseUserShareShockersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PauseUserShareShockersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'shockers': json['shockers'],
        'pause': json['pause'],
    };
}

export function PauseUserShareShockersRequestToJSON(json: any): PauseUserShareShockersRequest {
    return PauseUserShareShockersRequestToJSONTyped(json, false);
}

export function PauseUserShareShockersRequestToJSONTyped(value?: PauseUserShareShockersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shockers': value['shockers'],
        'pause': value['pause'],
    };
}

