/* tslint:disable */
/* eslint-disable */
/**
 * OpenShock.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveUserSharesResponse
 */
export interface RemoveUserSharesResponse {
    /**
     * 
     * @type {number}
     * @memberof RemoveUserSharesResponse
     */
    affectedRecords: number;
}

/**
 * Check if a given object implements the RemoveUserSharesResponse interface.
 */
export function instanceOfRemoveUserSharesResponse(value: object): value is RemoveUserSharesResponse {
    if (!('affectedRecords' in value) || value['affectedRecords'] === undefined) return false;
    return true;
}

export function RemoveUserSharesResponseFromJSON(json: any): RemoveUserSharesResponse {
    return RemoveUserSharesResponseFromJSONTyped(json, false);
}

export function RemoveUserSharesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveUserSharesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'affectedRecords': json['affectedRecords'],
    };
}

export function RemoveUserSharesResponseToJSON(json: any): RemoveUserSharesResponse {
    return RemoveUserSharesResponseToJSONTyped(json, false);
}

export function RemoveUserSharesResponseToJSONTyped(value?: RemoveUserSharesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affectedRecords': value['affectedRecords'],
    };
}

