// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.openshock.app' | 'https://api.openshock.dev' | 'https://localhost' | (string & {});
};

export type BasicUserInfo = {
    id: string;
    name: string;
    image: string;
};

export type BulkUserShareShockersUpdateRequest = {
    permissions: ShockerPermissions;
    limits: ShockerLimits;
    shockers: Array<string>;
};

export type ChangeUsernameRequest = {
    username: string;
};

export type Control = {
    id: string;
    type: ControlType;
    intensity: number;
    duration: number;
    exclusive?: boolean;
};

export type ControlRequest = {
    shocks: Array<Control>;
    customName?: string | null;
};

export const ControlType = {
    Stop: 'Stop',
    Shock: 'Shock',
    Vibrate: 'Vibrate',
    Sound: 'Sound'
} as const;

export type ControlType = typeof ControlType[keyof typeof ControlType];

export type CreateShareRequest = {
    shockers: Array<ShockerPermLimitPairWithId>;
    user?: string | null;
};

export type HubCreateRequest = {
    name: string;
};

export type LcgNodeResponseV2 = {
    host: string;
    port: number;
    path: string;
    country: string;
};

export type LegacyEmptyResponse = {
    message: string;
    data?: unknown;
};

export type LoginV2 = {
    password: string;
    usernameOrEmail: string;
    turnstileResponse: string;
};

export type LoginV2OkResponse = {
    accountId: string;
    accountName: string;
    accountEmail: string;
    isVerified: boolean;
    profileImage: string;
    accountRoles: Array<RoleType>;
};

export type OpenShockProblem = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    /**
     * @deprecated
     */
    readonly message?: string;
    /**
     * @deprecated
     */
    readonly traceId?: string | null;
    readonly requestId?: string | null;
    [key: string]: unknown;
};

export type PasswordResetRequestV2 = {
    email: string;
    turnstileResponse: string;
};

export type PauseUserShareShockersRequest = {
    shockers: Array<string>;
    pause: boolean;
};

export type PauseUserShareShockersResponse = {
    affectedRecords: number;
    pauseStates: {
        [key: string]: number;
    };
};

export type RemoveUserSharesResponse = {
    affectedRecords: number;
};

export const RoleType = {
    Support: 'Support',
    Staff: 'Staff',
    Admin: 'Admin',
    System: 'System'
} as const;

export type RoleType = typeof RoleType[keyof typeof RoleType];

export type ShareInviteBaseDetails = {
    id: string;
    createdAt: Temporal.Instant;
    owner: BasicUserInfo;
    sharedWith: BasicUserInfo;
    shockers: Array<ShockerPermLimitPairWithIdAndName>;
};

export type ShockerLimits = {
    intensity: number | null;
    duration: number | null;
};

export type ShockerPermLimitPairWithId = {
    permissions: ShockerPermissions;
    limits: ShockerLimits;
    id?: string;
};

export type ShockerPermLimitPairWithIdAndName = {
    permissions: ShockerPermissions;
    limits: ShockerLimits;
    id?: string;
    name: string;
};

export type ShockerPermissions = {
    vibrate: boolean;
    sound: boolean;
    shock: boolean;
    live?: boolean;
};

export type SignUpV2 = {
    username: string;
    password: string;
    email: string;
    turnstileResponse: string;
};

export type UserShareInfo = {
    id: string;
    name: string;
    createdOn: Temporal.Instant;
    permissions: ShockerPermissions;
    limits: ShockerLimits;
    /**
     * PauseReason
     *
     * An integer representing the reason(s) for the shocker being paused, expressed as a bitfield where reasons are OR'd together.
     *
     * Each bit corresponds to:
     * - 1: Shocker
     * - 2: UserShare
     * - 4: PublicShare
     *
     * For example, a value of 6 (2 | 4) indicates both 'UserShare' and 'PublicShare' reasons.
     */
    paused: number;
};

export const UsernameAvailability = {
    Available: 'Available',
    Taken: 'Taken',
    Invalid: 'Invalid'
} as const;

export type UsernameAvailability = typeof UsernameAvailability[keyof typeof UsernameAvailability];

export type UsernameCheckResponse = {
    availability: UsernameAvailability;
    error?: UsernameError;
};

export type UsernameError = {
    message: string;
    type: UsernameErrorType;
};

export const UsernameErrorType = {
    TooShort: 'TooShort',
    TooLong: 'TooLong',
    StartOrEndWithWhitespace: 'StartOrEndWithWhitespace',
    ResembleEmail: 'ResembleEmail',
    ObnoxiousCharacters: 'ObnoxiousCharacters',
    Blacklisted: 'Blacklisted'
} as const;

export type UsernameErrorType = typeof UsernameErrorType[keyof typeof UsernameErrorType];

export type V2UserShares = {
    outgoing: Array<V2UserSharesListItem>;
    incoming: Array<V2UserSharesListItem>;
};

export type V2UserSharesListItem = {
    id: string;
    name: string;
    image: string;
    shares: Array<UserShareInfo>;
};

export type OpenShockProblemWritable = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type AccountCheckUsernameData = {
    body?: ChangeUsernameRequest;
    path?: never;
    query?: never;
    url: '/2/account/username/check';
};

export type AccountCheckUsernameResponses = {
    /**
     * OK
     */
    200: UsernameCheckResponse;
};

export type AccountCheckUsernameResponse = AccountCheckUsernameResponses[keyof AccountCheckUsernameResponses];

export type AccountLoginV2Data = {
    body?: LoginV2;
    path?: never;
    query?: never;
    url: '/2/account/login';
};

export type AccountLoginV2Errors = {
    /**
     * Invalid username or password
     */
    401: OpenShockProblem;
    /**
     * Forbidden
     */
    403: OpenShockProblem;
};

export type AccountLoginV2Error = AccountLoginV2Errors[keyof AccountLoginV2Errors];

export type AccountLoginV2Responses = {
    /**
     * User successfully logged in
     */
    200: LoginV2OkResponse;
};

export type AccountLoginV2Response = AccountLoginV2Responses[keyof AccountLoginV2Responses];

export type AccountPasswordResetInitiateV2Data = {
    body?: PasswordResetRequestV2;
    path?: never;
    query?: never;
    url: '/2/account/reset-password';
};

export type AccountPasswordResetInitiateV2Errors = {
    /**
     * Forbidden
     */
    403: OpenShockProblem;
};

export type AccountPasswordResetInitiateV2Error = AccountPasswordResetInitiateV2Errors[keyof AccountPasswordResetInitiateV2Errors];

export type AccountPasswordResetInitiateV2Responses = {
    /**
     * Password reset email sent if the email is associated to an registered account
     */
    200: unknown;
};

export type AccountSignUpV2Data = {
    body?: SignUpV2;
    path?: never;
    query?: never;
    url: '/2/account/signup';
};

export type AccountSignUpV2Errors = {
    /**
     * Username or email already exists
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: OpenShockProblem;
    /**
     * Conflict
     */
    409: OpenShockProblem;
};

export type AccountSignUpV2Error = AccountSignUpV2Errors[keyof AccountSignUpV2Errors];

export type AccountSignUpV2Responses = {
    /**
     * User successfully signed up
     */
    200: unknown;
};

export type DeviceGetLiveControlGatewayV2Data = {
    body?: never;
    path?: never;
    query?: {
        version?: number;
    };
    url: '/2/device/assignLCG';
};

export type DeviceGetLiveControlGatewayV2Errors = {
    /**
     * Bad Request
     */
    400: OpenShockProblem;
    /**
     * Unable to find suitable LCG node
     */
    503: OpenShockProblem;
};

export type DeviceGetLiveControlGatewayV2Error = DeviceGetLiveControlGatewayV2Errors[keyof DeviceGetLiveControlGatewayV2Errors];

export type DeviceGetLiveControlGatewayV2Responses = {
    /**
     * Successfully assigned LCG node
     */
    200: LcgNodeResponseV2;
};

export type DeviceGetLiveControlGatewayV2Response = DeviceGetLiveControlGatewayV2Responses[keyof DeviceGetLiveControlGatewayV2Responses];

export type DevicesCreateDeviceV2Data = {
    body?: HubCreateRequest;
    path?: never;
    query?: never;
    url: '/2/devices';
};

export type DevicesCreateDeviceV2Responses = {
    /**
     * Successfully created device
     */
    201: string;
};

export type DevicesCreateDeviceV2Response = DevicesCreateDeviceV2Responses[keyof DevicesCreateDeviceV2Responses];

export type ShockerSendControlData = {
    body?: ControlRequest;
    path?: never;
    query?: never;
    url: '/2/shockers/control';
};

export type ShockerSendControlErrors = {
    /**
     * Forbidden
     */
    403: OpenShockProblem;
    /**
     * Not Found
     */
    404: OpenShockProblem;
    /**
     * Precondition Failed
     */
    412: OpenShockProblem;
};

export type ShockerSendControlError = ShockerSendControlErrors[keyof ShockerSendControlErrors];

export type ShockerSendControlResponses = {
    /**
     * The control messages were successfully sent.
     */
    200: LegacyEmptyResponse;
};

export type ShockerSendControlResponse = ShockerSendControlResponses[keyof ShockerSendControlResponses];

export type UserSharesCreateShareInviteData = {
    body?: CreateShareRequest;
    path?: never;
    query?: never;
    url: '/2/shares/user/invites';
};

export type UserSharesCreateShareInviteErrors = {
    /**
     * Bad Request
     */
    400: OpenShockProblem;
    /**
     * Not Found
     */
    404: OpenShockProblem;
};

export type UserSharesCreateShareInviteError = UserSharesCreateShareInviteErrors[keyof UserSharesCreateShareInviteErrors];

export type UserSharesCreateShareInviteResponses = {
    /**
     * OK
     */
    200: string;
};

export type UserSharesCreateShareInviteResponse = UserSharesCreateShareInviteResponses[keyof UserSharesCreateShareInviteResponses];

export type UserSharesGetSharesByUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/2/shares/user';
};

export type UserSharesGetSharesByUsersResponses = {
    /**
     * OK
     */
    200: V2UserShares;
};

export type UserSharesGetSharesByUsersResponse = UserSharesGetSharesByUsersResponses[keyof UserSharesGetSharesByUsersResponses];

export type UserSharesGetOutgoingInvitesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/2/shares/user/invites/outgoing';
};

export type UserSharesGetOutgoingInvitesListResponses = {
    /**
     * OK
     */
    200: Array<ShareInviteBaseDetails>;
};

export type UserSharesGetOutgoingInvitesListResponse = UserSharesGetOutgoingInvitesListResponses[keyof UserSharesGetOutgoingInvitesListResponses];

export type UserSharesGetIncomingInvitesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/2/shares/user/invites/incoming';
};

export type UserSharesGetIncomingInvitesListResponses = {
    /**
     * OK
     */
    200: Array<ShareInviteBaseDetails>;
};

export type UserSharesGetIncomingInvitesListResponse = UserSharesGetIncomingInvitesListResponses[keyof UserSharesGetIncomingInvitesListResponses];

export type UserSharesDeleteOutgoingInviteData = {
    body?: never;
    path: {
        inviteId: string;
    };
    query?: never;
    url: '/2/shares/user/invites/outgoing/{inviteId}';
};

export type UserSharesDeleteOutgoingInviteErrors = {
    /**
     * Not Found
     */
    404: OpenShockProblem;
};

export type UserSharesDeleteOutgoingInviteError = UserSharesDeleteOutgoingInviteErrors[keyof UserSharesDeleteOutgoingInviteErrors];

export type UserSharesDeleteOutgoingInviteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UserSharesDenyIncomingInviteData = {
    body?: never;
    path: {
        inviteId: string;
    };
    query?: never;
    url: '/2/shares/user/invites/incoming/{inviteId}';
};

export type UserSharesDenyIncomingInviteErrors = {
    /**
     * Not Found
     */
    404: OpenShockProblem;
};

export type UserSharesDenyIncomingInviteError = UserSharesDenyIncomingInviteErrors[keyof UserSharesDenyIncomingInviteErrors];

export type UserSharesDenyIncomingInviteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UserSharesRedeemInviteData = {
    body?: never;
    path: {
        inviteId: string;
    };
    query?: never;
    url: '/2/shares/user/invites/incoming/{inviteId}';
};

export type UserSharesRedeemInviteErrors = {
    /**
     * Not Found
     */
    404: OpenShockProblem;
};

export type UserSharesRedeemInviteError = UserSharesRedeemInviteErrors[keyof UserSharesRedeemInviteErrors];

export type UserSharesRedeemInviteResponses = {
    /**
     * OK
     */
    200: V2UserSharesListItem;
};

export type UserSharesRedeemInviteResponse = UserSharesRedeemInviteResponses[keyof UserSharesRedeemInviteResponses];

export type UserSharesBulkPauseUserShareShockersData = {
    body?: PauseUserShareShockersRequest;
    path: {
        userId: string;
    };
    query?: never;
    url: '/2/shares/user/{userId}/shockers/pause';
};

export type UserSharesBulkPauseUserShareShockersResponses = {
    /**
     * OK
     */
    200: PauseUserShareShockersResponse;
};

export type UserSharesBulkPauseUserShareShockersResponse = UserSharesBulkPauseUserShareShockersResponses[keyof UserSharesBulkPauseUserShareShockersResponses];

export type UserSharesBulkRemoveUserShareShockersData = {
    body?: Array<string>;
    path: {
        userId: string;
    };
    query?: never;
    url: '/2/shares/user/{userId}/shockers';
};

export type UserSharesBulkRemoveUserShareShockersResponses = {
    /**
     * OK
     */
    200: RemoveUserSharesResponse;
};

export type UserSharesBulkRemoveUserShareShockersResponse = UserSharesBulkRemoveUserShareShockersResponses[keyof UserSharesBulkRemoveUserShareShockersResponses];

export type UserSharesBulkUserShareShockersUpdateData = {
    body?: BulkUserShareShockersUpdateRequest;
    path: {
        userId: string;
    };
    query?: never;
    url: '/2/shares/user/{userId}/shockers';
};

export type UserSharesBulkUserShareShockersUpdateErrors = {
    /**
     * The share code does not exist or you do not have access to it.
     */
    404: OpenShockProblem;
};

export type UserSharesBulkUserShareShockersUpdateError = UserSharesBulkUserShareShockersUpdateErrors[keyof UserSharesBulkUserShareShockersUpdateErrors];

export type UserSharesBulkUserShareShockersUpdateResponses = {
    /**
     * Successfully updated share code
     */
    200: unknown;
};
