// This file is auto-generated by @hey-api/openapi-ts

import { Temporal } from 'temporal-polyfill';

export type ClientOptions = {
  baseUrl:
    'https://api.openshock.app' | 'https://api.openshock.dev' | 'https://localhost' | (string & {});
};

export type AddEmailProviderBlacklistDto = {
  domains: Array<string>;
};

export type AddUsernameBlacklistDto = {
  value: string;
  matchType: MatchTypeEnum;
};

export type AddWebhookDto = {
  name: string;
  url: string;
};

export type AdminOnlineDeviceResponse = {
  id: string;
  name: string;
  owner: BasicUserInfo;
  /**
   * SemVer
   *
   * Lightweight semantic version model with optional prerelease and build metadata.
   */
  firmwareVersion: string;
  gateway: string;
  connectedAt: Temporal.Instant;
  userAgent: null | string;
  bootedAt: Temporal.Instant;
  latencyMs: null | number;
  rssi: null | number;
  country: null | string;
  /**
   * IpAddress
   *
   * An IPv4 or IPv6 address in its textual form.
   */
  ip: null | string;
  asn: null | bigint;
  asnOrg: null | string;
};

export type AdminOnlineGatewayResponse = {
  id: string;
  host: string;
  port: number;
  pathPrefix: string;
  country: string;
  latitude: null | number;
  longitude: null | number;
  /**
   * Load the gateway advertises for hub assignment, in percent
   */
  load: number;
  environment: string;
  connectedHubs: number;
};

export type AdminUserView = {
  id: string;
  name: string;
  email: string;
  passwordHashType: PasswordHashingAlgorithm;
  roles: Array<RoleType>;
  createdAt: Temporal.Instant;
  activatedAt: null | Temporal.Instant;
  createdByAutomationTokenId: null | string;
  activationRequest: null | AdminUserViewUserActivationRequest;
  deactivation: null | AdminUserViewUserDeactivation;
  hubs: Array<AdminUserViewHub>;
  apiTokens: Array<AdminUserViewApiToken>;
  usersNameChanges: Array<AdminUserViewNameChange>;
  usersEmailChanges: Array<AdminUserViewEmailChange>;
  passwordResets: Array<AdminUserViewPasswordReset>;
  shockerControlLogsCount: number;
};

export type AdminUserViewApiToken = {
  id: string;
  name: string;
  permissions: Array<PermissionType>;
  validUntil: null | Temporal.Instant;
  lastUsed: null | Temporal.Instant;
  createdAt: Temporal.Instant;
  /**
   * IpAddress
   *
   * An IPv4 or IPv6 address in its textual form.
   */
  createdByIp: string;
};

export type AdminUserViewEmailChange = {
  id: string;
  email: string;
  createdAt: Temporal.Instant;
  usedAt: null | Temporal.Instant;
};

export type AdminUserViewHub = {
  id: string;
  name: string;
  createdAt: Temporal.Instant;
  shockers: Array<AdminUserViewShocker>;
};

export type AdminUserViewNameChange = {
  id: number;
  oldName: string;
  createdAt: Temporal.Instant;
};

export type AdminUserViewPasswordReset = {
  id: string;
  createdAt: Temporal.Instant;
  usedAt: null | Temporal.Instant;
};

export type AdminUserViewShocker = {
  id: string;
  name: string;
  createdAt: Temporal.Instant;
};

export type AdminUserViewUserActivationRequest = {
  emailSendAttempts: number;
  createdAt: Temporal.Instant;
};

export type AdminUserViewUserDeactivation = {
  deactivatedBy: AdminUserViewUserRef;
  scheduledDeletionTime: null | Temporal.Instant;
  deactivatedAt: Temporal.Instant;
};

export type AdminUserViewUserRef = {
  id: string;
  name: string;
};

export type AdminUsersView = {
  id: string;
  name: string;
  email: string;
  passwordHashType: null | PasswordHashingAlgorithm;
  roles: Array<RoleType>;
  createdAt: Temporal.Instant;
  activatedAt: null | Temporal.Instant;
  createdByAutomationTokenId: null | string;
  deactivatedAt: null | Temporal.Instant;
  deactivatedByUserId: null | string;
  apiTokenCount: number;
  passwordResetCount: number;
  shockerUserShareCount: number;
  shockerPublicShareCount: number;
  emailChangeRequestCount: number;
  nameChangeRequestCount: number;
  deviceCount: number;
  shockerCount: number;
  shockerControlLogCount: number;
};

export const AuditAction = {
  Login: 'Login',
  Logout: 'Logout',
  PasswordChanged: 'PasswordChanged',
  EmailChangeRequested: 'EmailChangeRequested',
  EmailChanged: 'EmailChanged',
  UsernameChanged: 'UsernameChanged',
  ApiTokenCreated: 'ApiTokenCreated',
  ApiTokenDeleted: 'ApiTokenDeleted',
  OAuthConnected: 'OAuthConnected',
  OAuthDisconnected: 'OAuthDisconnected',
  AccountDeactivated: 'AccountDeactivated',
  AccountReactivated: 'AccountReactivated',
  AccountDeleted: 'AccountDeleted',
  AutomationTokenCreated: 'AutomationTokenCreated',
  AutomationTokenUpdated: 'AutomationTokenUpdated',
  AutomationTokenRotated: 'AutomationTokenRotated',
  AutomationTokenDeleted: 'AutomationTokenDeleted',
  AutomationTokenUsed: 'AutomationTokenUsed',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export type AuditLogEntryResponse = {
  id: string;
  userId: string;
  actorId: null | string;
  action: AuditAction;
  reason: null | string;
  /**
   * IpAddress
   *
   * An IPv4 or IPv6 address in its textual form.
   */
  ipAddress: null | string;
  userAgent: null | string;
  metadata: null | AuditMetadata;
  createdAt: Temporal.Instant;
};

export type AuditMetadata =
  | ({
      t: 'login';
    } & AuditMetadataLoginMetadata)
  | ({
      t: 'usernameChanged';
    } & AuditMetadataUsernameChangedMetadata)
  | ({
      t: 'emailChangeRequested';
    } & AuditMetadataEmailChangeRequestedMetadata)
  | ({
      t: 'emailChanged';
    } & AuditMetadataEmailChangedMetadata)
  | ({
      t: 'apiTokenCreated';
    } & AuditMetadataApiTokenCreatedMetadata)
  | ({
      t: 'apiTokenDeleted';
    } & AuditMetadataApiTokenDeletedMetadata)
  | ({
      t: 'oauthConnected';
    } & AuditMetadataOAuthConnectedMetadata)
  | ({
      t: 'oauthDisconnected';
    } & AuditMetadataOAuthDisconnectedMetadata)
  | ({
      t: 'accountDeactivated';
    } & AuditMetadataAccountDeactivatedMetadata)
  | ({
      t: 'automationTokenCreated';
    } & AuditMetadataAutomationTokenCreatedMetadata)
  | ({
      t: 'automationTokenUpdated';
    } & AuditMetadataAutomationTokenUpdatedMetadata)
  | ({
      t: 'automationTokenRotated';
    } & AuditMetadataAutomationTokenRotatedMetadata)
  | ({
      t: 'automationTokenDeleted';
    } & AuditMetadataAutomationTokenDeletedMetadata)
  | ({
      t: 'automationTokenUsed';
    } & AuditMetadataAutomationTokenUsedMetadata);

export type AuditMetadataAccountDeactivatedMetadata = {
  t?: 'accountDeactivated';
  deleteLater: boolean;
};

export type AuditMetadataApiTokenCreatedMetadata = {
  t?: 'apiTokenCreated';
  tokenId: string;
  name: string;
  permissions: Array<string>;
};

export type AuditMetadataApiTokenDeletedMetadata = {
  t?: 'apiTokenDeleted';
  tokenId: string;
  name: string;
};

export type AuditMetadataAutomationTokenCreatedMetadata = {
  t?: 'automationTokenCreated';
  tokenId: string;
  name: string;
  types: Array<string>;
  autoCleanupUsers: boolean;
  autoCleanupAfter: null | string;
};

/**
 * The token was deleted together with the  accounts it created.
 */
export type AuditMetadataAutomationTokenDeletedMetadata = {
  t?: 'automationTokenDeleted';
  tokenId: string;
  name: string;
  deletedAccountCount: number;
};

export type AuditMetadataAutomationTokenRotatedMetadata = {
  t?: 'automationTokenRotated';
  tokenId: string;
  name: string;
};

/**
 * The token's settings after the update.
 */
export type AuditMetadataAutomationTokenUpdatedMetadata = {
  t?: 'automationTokenUpdated';
  tokenId: string;
  name: string;
  types: Array<string>;
  autoCleanupUsers: boolean;
  autoCleanupAfter: null | string;
};

/**
 * An automation token was used on this account.  is a `AutomationTokenFlow` name.
 */
export type AuditMetadataAutomationTokenUsedMetadata = {
  t?: 'automationTokenUsed';
  tokenId: string;
  name: string;
  flow: string;
};

export type AuditMetadataEmailChangeRequestedMetadata = {
  t?: 'emailChangeRequested';
  newEmail: string;
};

export type AuditMetadataEmailChangedMetadata = {
  t?: 'emailChanged';
  old: string;
  new: string;
};

export type AuditMetadataLoginMetadata = {
  t?: 'login';
  sessionId: string;
};

export type AuditMetadataOAuthConnectedMetadata = {
  t?: 'oauthConnected';
  provider: string;
};

export type AuditMetadataOAuthDisconnectedMetadata = {
  t?: 'oauthDisconnected';
  provider: string;
};

export type AuditMetadataUsernameChangedMetadata = {
  t?: 'usernameChanged';
  old: string;
  new: string;
};

export type AutomationTokenDto = {
  id: string;
  name: string;
  types: Array<AutomationTokenType>;
  createdAt: Temporal.Instant;
  lastUsedAt?: null | Temporal.Instant;
  lastRotatedAt?: null | Temporal.Instant;
  useCount?: bigint;
  autoCleanupUsers?: boolean;
  autoCleanupAfter?: null | string;
};

/**
 * A protection that an automation token is allowed to switch off.
 */
export const AutomationTokenType = { Turnstile: 'Turnstile', RateLimit: 'RateLimit' } as const;

/**
 * A protection that an automation token is allowed to switch off.
 */
export type AutomationTokenType = (typeof AutomationTokenType)[keyof typeof AutomationTokenType];

export type BackendInfoResponse = {
  version: string;
  commit: string;
  currentTime: Temporal.Instant;
  frontendUrl: string;
  shortLinkUrl: string;
  turnstileSiteKey: null | string;
  oAuthProviders: Array<string>;
  /**
   * False when the instance has no mail provider configured. Accounts are then activated on
   * creation, and no flow that relies on an emailed link (activation, password reset, email
   * change) can complete.
   */
  isMailEnabled: boolean;
  isUserAuthenticated: boolean;
};

export type BasicUserInfo = {
  id: string;
  name: string;
  image: string;
};

export type ChangeEmailRequest = {
  currentPassword: string;
  email: string;
};

export type ChangePasswordRequest = {
  currentPassword: string;
  newPassword: string;
};

export type ChangeUsernameRequest = {
  username: string;
};

/**
 * Request DTO for adding a new configuration item.
 */
export type ConfigurationAddItemRequest = {
  /**
   * The unique name of the configuration item.
   * Must consist of uppercase letters and underscores only.
   */
  name: string;
  /**
   * A human-readable description of the configuration item’s purpose.
   */
  description: string;
  /**
   * The data type of the configuration value.
   */
  type: ConfigurationValueType;
  /**
   * The initial value for the configuration item, serialized as a string.
   * Must conform to the format required by Type.
   */
  value: string;
};

/**
 * Data transfer object representing a configuration item.
 */
export type ConfigurationItemDto = {
  /**
   * The unique name of the configuration item.
   */
  name: string;
  /**
   * A human-readable description of what this configuration item controls.
   */
  description: string;
  /**
   * The data type of the configuration value.
   */
  type: ConfigurationValueType;
  /**
   * The current value of the configuration item, serialized as a string.
   */
  value: string;
  /**
   * The timestamp when the configuration was last updated.
   */
  updatedAt: Temporal.Instant;
  /**
   * The timestamp when the configuration was originally created.
   */
  createdAt: Temporal.Instant;
};

/**
 * Request DTO for updating a configuration item.
 * Either Description or Value (or both) may be provided.
 * If both are null, no update action is performed.
 */
export type ConfigurationUpdateItemRequest = {
  /**
   * The name of the configuration item to update.
   * Must consist only of uppercase letters and underscores.
   */
  name: string;
  /**
   * (Optional) New description for the configuration item.
   */
  description?: null | string;
  /**
   * (Optional) New value for the configuration item.
   * Must match the format expected by its existing ConfigurationValueType.
   */
  value?: null | string;
};

export const ConfigurationValueType = {
  String: 'String',
  Bool: 'Bool',
  Int: 'Int',
  Float: 'Float',
  Json: 'Json',
} as const;

export type ConfigurationValueType =
  (typeof ConfigurationValueType)[keyof typeof ConfigurationValueType];

export type Control = {
  id: string;
  type: ControlType;
  intensity: number;
  duration: number;
  /**
   * If true, overrides livecontrol
   */
  exclusive?: boolean;
};

export type ControlLogSenderLight = {
  id: string;
  name: string;
  image: string;
  customName: null | string;
};

export const ControlType = {
  Stop: 'Stop',
  Shock: 'Shock',
  Vibrate: 'Vibrate',
  Sound: 'Sound',
} as const;

export type ControlType = (typeof ControlType)[keyof typeof ControlType];

export type CreateAutomationTokenDto = {
  name: string;
  types: Array<AutomationTokenType>;
  /**
   * Whether the automated accounts this token creates are deleted once AutoCleanupAfter has
   * passed since they were created. Off by default; accounts the token didn't create are never deleted.
   */
  autoCleanupUsers?: boolean;
  autoCleanupAfter?: null | string;
};

export type CreateTokenRequest = {
  validUntil?: null | Temporal.Instant;
  name: string;
  permissions?: Array<PermissionType>;
};

export type CreatedAutomationTokenDto = {
  id: string;
  name: string;
  secret: string;
  types: Array<AutomationTokenType>;
  createdAt: Temporal.Instant;
  lastRotatedAt?: null | Temporal.Instant;
  autoCleanupUsers?: boolean;
  autoCleanupAfter?: null | string;
};

export type DeviceResponse = {
  id: string;
  name: string;
  createdOn: Temporal.Instant;
};

export type DeviceSelfResponse = {
  id: string;
  name: string;
  shockers: Array<MinimalShocker>;
};

export type DeviceWithShockersResponse = {
  shockers: Array<ShockerResponse>;
  id: string;
  name: string;
  createdOn: Temporal.Instant;
};

export type DeviceWithTokenResponse = {
  token: null | string;
  id: string;
  name: string;
  createdOn: Temporal.Instant;
};

export type EditTokenRequest = {
  name: string;
  permissions?: Array<PermissionType>;
};

/**
 * A set of email outbox message ids to apply a bulk requeue/cancel/delete to.
 */
export type EmailOutboxBulkRequest = {
  ids: Array<string>;
};

/**
 * Outcome of a bulk email outbox operation: how many ids were requested and how many rows were
 * actually affected (rows that were missing or in an ineligible state are silently not counted).
 */
export type EmailOutboxBulkResultDto = {
  requested: number;
  affected: number;
};

/**
 * An EmailOutboxMessage as exposed to admins on the mail-queue page. Mirrors the row
 * verbatim - the outbox stores no rendered body and no usable secret, so every field is safe to show.
 */
export type EmailOutboxMessageDto = {
  id: string;
  type: EmailType;
  recipient: string;
  recipientName: null | string;
  payload: {
    [key: string]: string;
  };
  coalesceKey: null | string;
  status: EmailStatus;
  attemptCount: number;
  nextAttemptAt: Temporal.Instant;
  lastError: null | string;
  createdAt: Temporal.Instant;
  sentAt: null | Temporal.Instant;
  failedAt: null | Temporal.Instant;
};

/**
 * Count of email outbox rows in each delivery state, for the admin mail-queue overview tiles.
 */
export type EmailOutboxStatsDto = {
  pending: bigint;
  sending: bigint;
  sent: bigint;
  failed: bigint;
  skipped: bigint;
  total: bigint;
};

export type EmailProviderBlacklistDto = {
  id: string;
  domain: string;
  createdAt: Temporal.Instant;
};

/**
 * Delivery state of an email outbox message.
 */
export const EmailStatus = {
  Pending: 'Pending',
  Sending: 'Sending',
  Sent: 'Sent',
  Failed: 'Failed',
  Skipped: 'Skipped',
} as const;

/**
 * Delivery state of an email outbox message.
 */
export type EmailStatus = (typeof EmailStatus)[keyof typeof EmailStatus];

/**
 * The kind of email an outbox message represents. The outbox stores
 * only the intent to send one of these, never a rendered body or a usable secret, the
 * consumer maps the type to the matching template and (for token-bearing types) mints a fresh
 * secret at send time.
 */
export const EmailType = {
  AccountActivation: 'AccountActivation',
  PasswordReset: 'PasswordReset',
  EmailVerification: 'EmailVerification',
  EmailChangeNotice: 'EmailChangeNotice',
} as const;

/**
 * The kind of email an outbox message represents. The outbox stores
 * only the intent to send one of these, never a rendered body or a usable secret, the
 * consumer maps the type to the matching template and (for token-bearing types) mints a fresh
 * secret at send time.
 */
export type EmailType = (typeof EmailType)[keyof typeof EmailType];

export type HubEditRequest = {
  name: string;
};

export type LcgNodeResponse = {
  fqdn: string;
  country: string;
};

export type LcgResponse = {
  gateway: string;
  country: string;
};

export type LegacyDataResponseOfArrayOfAdminOnlineDeviceResponse = {
  message: string;
  data: Array<AdminOnlineDeviceResponse>;
};

export type LegacyDataResponseOfArrayOfDeviceResponse = {
  message: string;
  data: Array<DeviceResponse>;
};

export type LegacyDataResponseOfArrayOfDeviceWithShockersResponse = {
  message: string;
  data: Array<DeviceWithShockersResponse>;
};

export type LegacyDataResponseOfArrayOfLogEntry = {
  message: string;
  data: Array<LogEntry>;
};

export type LegacyDataResponseOfArrayOfOwnPublicShareResponse = {
  message: string;
  data: Array<OwnPublicShareResponse>;
};

export type LegacyDataResponseOfArrayOfOwnerShockerResponse = {
  message: string;
  data: Array<OwnerShockerResponse>;
};

export type LegacyDataResponseOfArrayOfShareCodeInfo = {
  message: string;
  data: Array<ShareCodeInfo>;
};

export type LegacyDataResponseOfArrayOfShareInfo = {
  message: string;
  data: Array<ShareInfo>;
};

export type LegacyDataResponseOfArrayOfShockerResponse = {
  message: string;
  data: Array<ShockerResponse>;
};

export type LegacyDataResponseOfBackendInfoResponse = {
  message: string;
  data: BackendInfoResponse;
};

export type LegacyDataResponseOfDeviceSelfResponse = {
  message: string;
  data: DeviceSelfResponse;
};

export type LegacyDataResponseOfDeviceWithTokenResponse = {
  message: string;
  data: DeviceWithTokenResponse;
};

export type LegacyDataResponseOfGuid = {
  message: string;
  data: string;
};

export type LegacyDataResponseOfIReadOnlyCollectionOfOtaItem = {
  message: string;
  data: Array<OtaItem>;
};

export type LegacyDataResponseOfLcgNodeResponse = {
  message: string;
  data: LcgNodeResponse;
};

export type LegacyDataResponseOfLcgResponse = {
  message: string;
  data: LcgResponse;
};

export type LegacyDataResponseOfPauseReason = {
  message: string;
  /**
   * PauseReason
   *
   * An integer representing the reason(s) for the shocker being paused, expressed as a bitfield where reasons are OR'd together.
   *
   * Each bit corresponds to:
   * - 1: Shocker
   * - 2: UserShare
   * - 4: PublicShare
   *
   * For example, a value of 6 (2 | 4) indicates both 'UserShare' and 'PublicShare' reasons.
   */
  data: number;
};

export type LegacyDataResponseOfPublicShareResponse = {
  message: string;
  data: PublicShareResponse;
};

export type LegacyDataResponseOfShockerWithDevice = {
  message: string;
  data: ShockerWithDevice;
};

export type LegacyDataResponseOfStatsResponse = {
  message: string;
  data: StatsResponse;
};

export type LegacyDataResponseOfUserSelfResponse = {
  message: string;
  data: UserSelfResponse;
};

export type LegacyDataResponseOfboolean = {
  message: string;
  data: boolean;
};

export type LegacyDataResponseOfstring = {
  message: string;
  data: string;
};

export type LegacyEmptyResponse = {
  message: string;
  data?: unknown;
};

export type LogEntry = {
  id: string;
  createdOn: Temporal.Instant;
  type: ControlType;
  controlledBy: ControlLogSenderLight;
  intensity: number;
  duration: number;
};

export type LogEntryWithHub = {
  id: string;
  hubId: string;
  hubName: string;
  shockerId: string;
  shockerName: string;
  createdOn: Temporal.Instant;
  type: ControlType;
  controlledBy: ControlLogSenderLight;
  intensity: number;
  duration: number;
};

export type LoginSessionResponse = {
  id: string;
  /**
   * IpAddress
   *
   * An IPv4 or IPv6 address in its textual form.
   */
  ip: string;
  userAgent: string;
  created: Temporal.Instant;
  expires: Temporal.Instant;
  lastUsed: null | Temporal.Instant;
  asnOrg?: null | string;
  isVpn?: null | boolean;
  countryCode?: null | string;
  city?: null | string;
};

export const MatchTypeEnum = { Exact: 'Exact', Contains: 'Contains' } as const;

export type MatchTypeEnum = (typeof MatchTypeEnum)[keyof typeof MatchTypeEnum];

export type MinimalShocker = {
  id: string;
  rfId: number;
  model: ShockerModelType;
};

export type NewShocker = {
  name: string;
  rfId: number;
  device: string;
  model: ShockerModelType;
};

export type OAuthConnectionResponse = {
  providerKey: string;
  externalId: string;
  displayName: null | string;
  linkedAt: Temporal.Instant;
};

export type OpenShockProblem = {
  type: null | string;
  title: null | string;
  status?: null | number;
  detail?: null | string;
  instance?: null | string;
  /**
   * @deprecated
   */
  message?: string;
  /**
   * @deprecated
   */
  traceId?: null | string;
  requestId?: null | string;
};

export type OtaItem = {
  id: number;
  startedAt: Temporal.Instant;
  status: OtaUpdateStatus;
  /**
   * SemVer
   *
   * Lightweight semantic version model with optional prerelease and build metadata.
   */
  version: string;
  message: null | string;
};

export const OtaUpdateStatus = {
  Started: 'Started',
  Running: 'Running',
  Finished: 'Finished',
  Error: 'Error',
  Timeout: 'Timeout',
} as const;

export type OtaUpdateStatus = (typeof OtaUpdateStatus)[keyof typeof OtaUpdateStatus];

export type OwnPublicShareResponse = {
  id: string;
  name: string;
  createdOn: Temporal.Instant;
  expiresOn?: null | Temporal.Instant;
};

export type OwnerShockerResponse = {
  id: string;
  name: string;
  image: string;
  devices: Array<SharedDevice>;
};

/**
 * Page of results for a paginated list endpoint.
 */
export type PagedResultOfAuditLogEntryResponse = {
  /**
   * Items on the current page.
   */
  items: Array<AuditLogEntryResponse>;
  /**
   * 1-based current page index.
   */
  page: number;
  /**
   * Page size used to produce this result.
   */
  pageSize: number;
  /**
   * Total number of items across all pages matching the query.
   */
  totalCount: number;
  /**
   * Total number of pages. Always at least 1, even when  is zero.
   */
  totalPages?: number;
};

/**
 * Page of results for a paginated list endpoint.
 */
export type PagedResultOfLogEntryWithHub = {
  /**
   * Items on the current page.
   */
  items: Array<LogEntryWithHub>;
  /**
   * 1-based current page index.
   */
  page: number;
  /**
   * Page size used to produce this result.
   */
  pageSize: number;
  /**
   * Total number of items across all pages matching the query.
   */
  totalCount: number;
  /**
   * Total number of pages. Always at least 1, even when  is zero.
   */
  totalPages?: number;
};

export type PaginatedOfAdminUsersView = {
  offset: number;
  limit: number;
  total: bigint;
  data: Array<AdminUsersView>;
};

export type PaginatedOfEmailOutboxMessageDto = {
  offset: number;
  limit: number;
  total: bigint;
  data: Array<EmailOutboxMessageDto>;
};

export const PasswordHashingAlgorithm = {
  BCrypt: 'BCrypt',
  Pbkdf2: 'PBKDF2',
  Unknown: 'Unknown',
} as const;

export type PasswordHashingAlgorithm =
  (typeof PasswordHashingAlgorithm)[keyof typeof PasswordHashingAlgorithm];

export type PasswordResetProcessData = {
  password: string;
};

export type PatchAutomationTokenDto = {
  name?: null | string;
  types?: null | Array<AutomationTokenType>;
  autoCleanupUsers?: null | boolean;
  autoCleanupAfter?: null | string;
};

export type PauseRequest = {
  pause: boolean;
};

export const PermissionType = {
  ShockersUse: 'shockers.use',
  ShockersEdit: 'shockers.edit',
  ShockersPause: 'shockers.pause',
  DevicesEdit: 'devices.edit',
  DevicesAuth: 'devices.auth',
  UsersharesEdit: 'usershares.edit',
  UsersharesPause: 'usershares.pause',
  PublicsharesPause: 'publicshares.pause',
  PublicsharesEdit: 'publicshares.edit',
} as const;

export type PermissionType = (typeof PermissionType)[keyof typeof PermissionType];

export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number;
  detail?: null | string;
  instance?: null | string;
};

export type PublicShareCreate = {
  name: string;
  expiresOn?: null | Temporal.Instant;
};

export type PublicShareDevice = {
  id: string;
  name: string;
  shockers: Array<PublicShareShocker>;
};

export type PublicShareEditShocker = {
  permissions: ShockerPermissions;
  limits: ShockerLimits;
  cooldown?: null | number;
};

export type PublicShareResponse = {
  id: string;
  name: string;
  createdOn: Temporal.Instant;
  expiresOn?: null | Temporal.Instant;
  author: BasicUserInfo;
  devices?: Array<PublicShareDevice>;
};

export type PublicShareShocker = {
  id: string;
  name: string;
  permissions: ShockerPermissions;
  limits: ShockerLimits;
  /**
   * PauseReason
   *
   * An integer representing the reason(s) for the shocker being paused, expressed as a bitfield where reasons are OR'd together.
   *
   * Each bit corresponds to:
   * - 1: Shocker
   * - 2: UserShare
   * - 4: PublicShare
   *
   * For example, a value of 6 (2 | 4) indicates both 'UserShare' and 'PublicShare' reasons.
   */
  paused: number;
};

export type ReportTokensRequest = {
  turnstileResponse: string;
  secrets: Array<string>;
};

export const RoleType = {
  Support: 'Support',
  Staff: 'Staff',
  Admin: 'Admin',
  System: 'System',
} as const;

export type RoleType = (typeof RoleType)[keyof typeof RoleType];

/**
 * Request to enqueue a preview/test email of a chosen type to a chosen address. The message is
 * delivered by the Cron pipeline with placeholder data and a dummy link (no token, no request row).
 */
export type SendTestEmailDto = {
  /**
   * Which template to preview.
   */
  type: EmailType;
  /**
   * Destination address for the test email.
   */
  recipient: string;
  /**
   * Optional display name for the recipient.
   */
  recipientName?: null | string;
};

export type SetUserEmailRequestBody = {
  email: string;
};

export type SetUserNameRequestBody = {
  name: string;
};

export type SetUserPasswordRequestBody = {
  password: string;
};

export type ShareCodeInfo = {
  id: string;
  createdOn: Temporal.Instant;
};

export type ShareInfo = {
  sharedWith: BasicUserInfo;
  createdOn: Temporal.Instant;
  permissions: ShockerPermissions;
  limits: ShockerLimits;
  paused: boolean;
};

export type SharedDevice = {
  id: string;
  name: string;
  shockers: Array<SharedShocker>;
};

export type SharedShocker = {
  id: string;
  name: string;
  isPaused: boolean;
  permissions: ShockerPermissions;
  limits: ShockerLimits;
};

export type ShockerLimits = {
  intensity: null | number;
  duration: null | number;
};

export const ShockerModelType = {
  CaiXianlin: 'CaiXianlin',
  PetTrainer: 'PetTrainer',
  Petrainer998Dr: 'Petrainer998DR',
  WellturnT330: 'WellturnT330',
} as const;

export type ShockerModelType = (typeof ShockerModelType)[keyof typeof ShockerModelType];

export type ShockerPermLimitPair = {
  permissions: ShockerPermissions;
  limits: ShockerLimits;
};

export type ShockerPermissions = {
  vibrate: boolean;
  sound: boolean;
  shock: boolean;
  live?: boolean;
};

export type ShockerResponse = {
  name: string;
  isPaused: boolean;
  createdOn: Temporal.Instant;
  id: string;
  rfId: number;
  model: ShockerModelType;
};

export type ShockerWithDevice = {
  device: string;
  name: string;
  isPaused: boolean;
  createdOn: Temporal.Instant;
  id: string;
  rfId: number;
  model: ShockerModelType;
};

/**
 * Sort direction for list endpoints.
 */
export const SortDirection = { Asc: 'Asc', Desc: 'Desc' } as const;

/**
 * Sort direction for list endpoints.
 */
export type SortDirection = (typeof SortDirection)[keyof typeof SortDirection];

export type StatsResponse = {
  devicesOnline: bigint;
};

export type TokenCreatedResponse = {
  id: string;
  name: string;
  token: string;
  createdAt: Temporal.Instant;
  validUntil: null | Temporal.Instant;
  lastUsed: Temporal.Instant;
  permissions: Array<PermissionType>;
};

export type TokenResponse = {
  id: string;
  name: string;
  createdOn: Temporal.Instant;
  validUntil: null | Temporal.Instant;
  lastUsed: Temporal.Instant;
  permissions: Array<PermissionType>;
};

export type UserNameBlacklistDto = {
  id: string;
  value: string;
  matchType: MatchTypeEnum;
  createdAt: Temporal.Instant;
};

export type UserPatchDto = {
  name?: null | string;
  email?: null | string;
};

export type UserSelfResponse = {
  id: string;
  name: string;
  email: string;
  image: string;
  roles: Array<RoleType>;
  rank: string;
  hasPassword: boolean;
};

export const UsernameAvailability = {
  Available: 'Available',
  Taken: 'Taken',
  Invalid: 'Invalid',
} as const;

export type UsernameAvailability = (typeof UsernameAvailability)[keyof typeof UsernameAvailability];

export type UsernameCheckResponse = {
  availability: UsernameAvailability;
  error?: null | UsernameError;
};

export type UsernameError = {
  message: string;
  type: UsernameErrorType;
};

export const UsernameErrorType = {
  TooShort: 'TooShort',
  TooLong: 'TooLong',
  StartOrEndWithWhitespace: 'StartOrEndWithWhitespace',
  ResembleEmail: 'ResembleEmail',
  ObnoxiousCharacters: 'ObnoxiousCharacters',
  Blacklisted: 'Blacklisted',
} as const;

export type UsernameErrorType = (typeof UsernameErrorType)[keyof typeof UsernameErrorType];

export type WebhookDto = {
  id: string;
  name: string;
  url: string;
  createdAt: Temporal.Instant;
};

export type VersionGetBackendInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1';
};

export type VersionGetBackendInfoResponses = {
  /**
   * The version was successfully retrieved.
   */
  200: LegacyDataResponseOfBackendInfoResponse;
};

export type VersionGetBackendInfoResponse =
  VersionGetBackendInfoResponses[keyof VersionGetBackendInfoResponses];

export type UsersGetSelfData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/users/self';
};

export type UsersGetSelfResponses = {
  /**
   * The user's information was successfully retrieved.
   */
  200: LegacyDataResponseOfUserSelfResponse;
};

export type UsersGetSelfResponse = UsersGetSelfResponses[keyof UsersGetSelfResponses];

export type UsersGetByNameData = {
  body?: never;
  path: {
    username: string;
  };
  query?: never;
  url: '/1/users/by-name/{username}';
};

export type UsersGetByNameErrors = {
  /**
   * Not Found
   */
  404: OpenShockProblem;
};

export type UsersGetByNameError = UsersGetByNameErrors[keyof UsersGetByNameErrors];

export type UsersGetByNameResponses = {
  /**
   * OK
   */
  200: BasicUserInfo;
};

export type UsersGetByNameResponse = UsersGetByNameResponses[keyof UsersGetByNameResponses];

export type TokenDeleteDeleteTokenData = {
  body?: never;
  path: {
    /**
     * Revoke a token
     */
    tokenId: string;
  };
  query?: never;
  url: '/1/tokens/{tokenId}';
};

export type TokenDeleteDeleteTokenErrors = {
  /**
   * Api Token is not allowed to delete other Api Tokens
   */
  403: ProblemDetails;
  /**
   * The token does not exist, or you do not have access to it
   */
  404: OpenShockProblem;
};

export type TokenDeleteDeleteTokenError =
  TokenDeleteDeleteTokenErrors[keyof TokenDeleteDeleteTokenErrors];

export type TokenDeleteDeleteTokenResponses = {
  /**
   * Successfully deleted token
   */
  200: unknown;
};

export type TokensGetTokenByIdData = {
  body?: never;
  path: {
    /**
     * Get a token by id
     */
    tokenId: string;
  };
  query?: never;
  url: '/1/tokens/{tokenId}';
};

export type TokensGetTokenByIdErrors = {
  /**
   * The token does not exist or you do not have access to it.
   */
  404: OpenShockProblem;
};

export type TokensGetTokenByIdError = TokensGetTokenByIdErrors[keyof TokensGetTokenByIdErrors];

export type TokensGetTokenByIdResponses = {
  /**
   * The token
   */
  200: TokenResponse;
};

export type TokensGetTokenByIdResponse =
  TokensGetTokenByIdResponses[keyof TokensGetTokenByIdResponses];

export type TokensEditTokenData = {
  body: EditTokenRequest;
  path: {
    /**
     * Edit a token
     */
    tokenId: string;
  };
  query?: never;
  url: '/1/tokens/{tokenId}';
};

export type TokensEditTokenErrors = {
  /**
   * The token does not exist or you do not have access to it.
   */
  404: OpenShockProblem;
};

export type TokensEditTokenError = TokensEditTokenErrors[keyof TokensEditTokenErrors];

export type TokensEditTokenResponses = {
  /**
   * The edited token
   */
  200: unknown;
};

export type TokensSelfGetSelfTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/tokens/self';
};

export type TokensSelfGetSelfTokenResponses = {
  /**
   * OK
   */
  200: TokenResponse;
};

export type TokensSelfGetSelfTokenResponse =
  TokensSelfGetSelfTokenResponses[keyof TokensSelfGetSelfTokenResponses];

export type TokensReportTokensData = {
  body: ReportTokensRequest;
  path?: never;
  query?: never;
  url: '/1/tokens/report';
};

export type TokensReportTokensResponses = {
  /**
   * The tokens were deleted if found
   */
  200: unknown;
};

export type TokensListTokensData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/tokens';
};

export type TokensListTokensResponses = {
  /**
   * All tokens for the current user
   */
  200: Array<TokenResponse>;
};

export type TokensListTokensResponse = TokensListTokensResponses[keyof TokensListTokensResponses];

export type TokensCreateTokenData = {
  body: CreateTokenRequest;
  path?: never;
  query?: never;
  url: '/1/tokens';
};

export type TokensCreateTokenResponses = {
  /**
   * The created token
   */
  200: TokenCreatedResponse;
};

export type TokensCreateTokenResponse =
  TokensCreateTokenResponses[keyof TokensCreateTokenResponses];

export type ShockerRemoveShockerData = {
  body?: never;
  path: {
    /**
     * Remove a shocker
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}';
};

export type ShockerRemoveShockerErrors = {
  /**
   * Shocker does not exist
   */
  404: OpenShockProblem;
};

export type ShockerRemoveShockerError =
  ShockerRemoveShockerErrors[keyof ShockerRemoveShockerErrors];

export type ShockerRemoveShockerResponses = {
  /**
   * Successfully deleted shocker
   */
  200: LegacyEmptyResponse;
};

export type ShockerRemoveShockerResponse =
  ShockerRemoveShockerResponses[keyof ShockerRemoveShockerResponses];

export type ShockerGetShockerByIdData = {
  body?: never;
  path: {
    /**
     * Get information about a shocker.
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}';
};

export type ShockerGetShockerByIdErrors = {
  /**
   * The shocker does not exist or you do not have access to it.
   */
  404: OpenShockProblem;
};

export type ShockerGetShockerByIdError =
  ShockerGetShockerByIdErrors[keyof ShockerGetShockerByIdErrors];

export type ShockerGetShockerByIdResponses = {
  /**
   * The shocker information was successfully retrieved.
   */
  200: LegacyDataResponseOfShockerWithDevice;
};

export type ShockerGetShockerByIdResponse =
  ShockerGetShockerByIdResponses[keyof ShockerGetShockerByIdResponses];

export type ShockerEditShockerData = {
  body: NewShocker;
  path: {
    /**
     * Edit a shocker
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}';
};

export type ShockerEditShockerErrors = {
  /**
   * Shocker does not exist
   */
  404: OpenShockProblem;
};

export type ShockerEditShockerError = ShockerEditShockerErrors[keyof ShockerEditShockerErrors];

export type ShockerEditShockerResponses = {
  /**
   * Successfully updated shocker
   */
  200: LegacyEmptyResponse;
};

export type ShockerEditShockerResponse =
  ShockerEditShockerResponses[keyof ShockerEditShockerResponses];

export type ShockerGetShockerLogsData = {
  body?: never;
  path: {
    /**
     * Get the logs for a shocker
     */
    shockerId: string;
  };
  query?: {
    /**
     * Get the logs for a shocker
     */
    offset?: number;
    /**
     * Get the logs for a shocker
     */
    limit?: number;
  };
  url: '/1/shockers/{shockerId}/logs';
};

export type ShockerGetShockerLogsErrors = {
  /**
   * Shocker does not exist
   */
  404: OpenShockProblem;
};

export type ShockerGetShockerLogsError =
  ShockerGetShockerLogsErrors[keyof ShockerGetShockerLogsErrors];

export type ShockerGetShockerLogsResponses = {
  /**
   * The logs
   */
  200: LegacyDataResponseOfArrayOfLogEntry;
};

export type ShockerGetShockerLogsResponse =
  ShockerGetShockerLogsResponses[keyof ShockerGetShockerLogsResponses];

export type ShockerGetAllShockerLogsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page, sort, and search parameters. Supported sort keys: createdOn (default), intensity, duration, type, hubName, shockerName.
     */
    page?: number;
    /**
     * Page, sort, and search parameters. Supported sort keys: createdOn (default), intensity, duration, type, hubName, shockerName.
     */
    pageSize?: number;
    /**
     * Page, sort, and search parameters. Supported sort keys: createdOn (default), intensity, duration, type, hubName, shockerName.
     */
    search?: string;
    /**
     * Page, sort, and search parameters. Supported sort keys: createdOn (default), intensity, duration, type, hubName, shockerName.
     */
    sort?: string;
    /**
     * Page, sort, and search parameters. Supported sort keys: createdOn (default), intensity, duration, type, hubName, shockerName.
     */
    sortDir?: SortDirection;
    /**
     * Optional shocker ID filter. When omitted or empty, logs for all of the caller's shockers are returned.
     */
    shockerIds?: Array<string>;
  };
  url: '/1/shockers/logs';
};

export type ShockerGetAllShockerLogsResponses = {
  /**
   * A page of logs.
   */
  200: PagedResultOfLogEntryWithHub;
};

export type ShockerGetAllShockerLogsResponse =
  ShockerGetAllShockerLogsResponses[keyof ShockerGetAllShockerLogsResponses];

export type ShockerListSharedShockersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/shockers/shared';
};

export type ShockerListSharedShockersResponses = {
  /**
   * The shockers were successfully retrieved.
   */
  200: LegacyDataResponseOfArrayOfOwnerShockerResponse;
};

export type ShockerListSharedShockersResponse =
  ShockerListSharedShockersResponses[keyof ShockerListSharedShockersResponses];

export type ShockerListShockersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/shockers/own';
};

export type ShockerListShockersResponses = {
  /**
   * The shockers were successfully retrieved.
   */
  200: LegacyDataResponseOfArrayOfDeviceWithShockersResponse;
};

export type ShockerListShockersResponse =
  ShockerListShockersResponses[keyof ShockerListShockersResponses];

export type ShockerPauseShockerData = {
  body: PauseRequest;
  path: {
    /**
     * Pause or unpause a shocker
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}/pause';
};

export type ShockerPauseShockerErrors = {
  /**
   * Shocker not found or does not belong to you
   */
  404: OpenShockProblem;
};

export type ShockerPauseShockerError = ShockerPauseShockerErrors[keyof ShockerPauseShockerErrors];

export type ShockerPauseShockerResponses = {
  /**
   * Successfully set pause state
   */
  200: LegacyDataResponseOfboolean;
};

export type ShockerPauseShockerResponse =
  ShockerPauseShockerResponses[keyof ShockerPauseShockerResponses];

export type ShockerRegisterShockerData = {
  body: NewShocker;
  path?: never;
  query?: never;
  url: '/1/shockers';
};

export type ShockerRegisterShockerErrors = {
  /**
   * You can have a maximum of 11 Shockers per Device.
   */
  400: OpenShockProblem;
  /**
   * Device does not exist
   */
  404: OpenShockProblem;
};

export type ShockerRegisterShockerError =
  ShockerRegisterShockerErrors[keyof ShockerRegisterShockerErrors];

export type ShockerRegisterShockerResponses = {
  /**
   * Successfully created shocker
   */
  201: LegacyDataResponseOfGuid;
};

export type ShockerRegisterShockerResponse =
  ShockerRegisterShockerResponses[keyof ShockerRegisterShockerResponses];

export type ShockerSendControlDeprecatedData = {
  body: Array<Control>;
  path?: never;
  query?: never;
  url: '/1/shockers/control';
};

export type ShockerSendControlDeprecatedErrors = {
  /**
   * Forbidden
   */
  403: OpenShockProblem;
  /**
   * Not Found
   */
  404: OpenShockProblem;
  /**
   * Precondition Failed
   */
  412: OpenShockProblem;
};

export type ShockerSendControlDeprecatedError =
  ShockerSendControlDeprecatedErrors[keyof ShockerSendControlDeprecatedErrors];

export type ShockerSendControlDeprecatedResponses = {
  /**
   * The control messages were successfully sent.
   */
  200: LegacyEmptyResponse;
};

export type ShockerSendControlDeprecatedResponse =
  ShockerSendControlDeprecatedResponses[keyof ShockerSendControlDeprecatedResponses];

export type ShockerGetUserSharesData = {
  body?: never;
  path: {
    /**
     * Id of the shocker
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}/shares';
};

export type ShockerGetUserSharesErrors = {
  /**
   * The shocker does not exist or you do not have access to it.
   */
  404: OpenShockProblem;
};

export type ShockerGetUserSharesError =
  ShockerGetUserSharesErrors[keyof ShockerGetUserSharesErrors];

export type ShockerGetUserSharesResponses = {
  /**
   * OK
   */
  200: LegacyDataResponseOfArrayOfShareInfo;
};

export type ShockerGetUserSharesResponse =
  ShockerGetUserSharesResponses[keyof ShockerGetUserSharesResponses];

export type ShockerShockerShareCodeCreateData = {
  body: ShockerPermLimitPair;
  path: {
    /**
     * Create a share code for a shocker
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}/shares';
};

export type ShockerShockerShareCodeCreateErrors = {
  /**
   * Shocker does not exists or you do not have access to it.
   */
  404: OpenShockProblem;
};

export type ShockerShockerShareCodeCreateError =
  ShockerShockerShareCodeCreateErrors[keyof ShockerShockerShareCodeCreateErrors];

export type ShockerShockerShareCodeCreateResponses = {
  /**
   * The share code was successfully created.
   */
  200: LegacyDataResponseOfGuid;
};

export type ShockerShockerShareCodeCreateResponse =
  ShockerShockerShareCodeCreateResponses[keyof ShockerShockerShareCodeCreateResponses];

export type ShockerShockerShareCodeListData = {
  body?: never;
  path: {
    /**
     * List all share codes for a shocker
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}/shareCodes';
};

export type ShockerShockerShareCodeListErrors = {
  /**
   * Not Found
   */
  404: OpenShockProblem;
};

export type ShockerShockerShareCodeListError =
  ShockerShockerShareCodeListErrors[keyof ShockerShockerShareCodeListErrors];

export type ShockerShockerShareCodeListResponses = {
  /**
   * OK
   */
  200: LegacyDataResponseOfArrayOfShareCodeInfo;
};

export type ShockerShockerShareCodeListResponse =
  ShockerShockerShareCodeListResponses[keyof ShockerShockerShareCodeListResponses];

export type ShockerShockerShareRemoveData = {
  body?: never;
  path: {
    /**
     * Remove a share for a shocker
     */
    shockerId: string;
    /**
     * Remove a share for a shocker
     */
    sharedWithUserId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}/shares/{sharedWithUserId}';
};

export type ShockerShockerShareRemoveErrors = {
  /**
   * Share does not exists or device/shocker does not belong to you nor is shared with you
   */
  404: OpenShockProblem;
};

export type ShockerShockerShareRemoveError =
  ShockerShockerShareRemoveErrors[keyof ShockerShockerShareRemoveErrors];

export type ShockerShockerShareRemoveResponses = {
  /**
   * Successfully removed share code
   */
  200: unknown;
};

export type ShockerShockerShareCodeUpdateData = {
  body: ShockerPermLimitPair;
  path: {
    /**
     * Update a share for a shocker
     */
    shockerId: string;
    /**
     * Update a share for a shocker
     */
    sharedWithUserId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}/shares/{sharedWithUserId}';
};

export type ShockerShockerShareCodeUpdateErrors = {
  /**
   * The share code does not exist or you do not have access to it.
   */
  404: OpenShockProblem;
};

export type ShockerShockerShareCodeUpdateError =
  ShockerShockerShareCodeUpdateErrors[keyof ShockerShockerShareCodeUpdateErrors];

export type ShockerShockerShareCodeUpdateResponses = {
  /**
   * Successfully updated share code
   */
  200: unknown;
};

export type ShockerShockerShareCodePauseData = {
  body: PauseRequest;
  path: {
    /**
     * Pause/Unpause a share code for a shocker
     */
    shockerId: string;
    /**
     * Pause/Unpause a share code for a shocker
     */
    sharedWithUserId: string;
  };
  query?: never;
  url: '/1/shockers/{shockerId}/shares/{sharedWithUserId}/pause';
};

export type ShockerShockerShareCodePauseErrors = {
  /**
   * The share code does not exist or you do not have access to it.
   */
  404: OpenShockProblem;
};

export type ShockerShockerShareCodePauseError =
  ShockerShockerShareCodePauseErrors[keyof ShockerShockerShareCodePauseErrors];

export type ShockerShockerShareCodePauseResponses = {
  /**
   * Successfully updated pause status share
   */
  200: LegacyDataResponseOfboolean;
};

export type ShockerShockerShareCodePauseResponse =
  ShockerShockerShareCodePauseResponses[keyof ShockerShockerShareCodePauseResponses];

export type SharesDeleteShareCodeData = {
  body?: never;
  path: {
    /**
     * Delete a share code
     */
    shareCodeId: string;
  };
  query?: never;
  url: '/1/shares/code/{shareCodeId}';
};

export type SharesDeleteShareCodeErrors = {
  /**
   * Share code not found or does not belong to you
   */
  404: OpenShockProblem;
};

export type SharesDeleteShareCodeError =
  SharesDeleteShareCodeErrors[keyof SharesDeleteShareCodeErrors];

export type SharesDeleteShareCodeResponses = {
  /**
   * Deleted share code
   */
  200: LegacyEmptyResponse;
};

export type SharesDeleteShareCodeResponse =
  SharesDeleteShareCodeResponses[keyof SharesDeleteShareCodeResponses];

export type SharesLinkShareCodeData = {
  body?: never;
  path: {
    /**
     * Link a share code to your account
     */
    shareCodeId: string;
  };
  query?: never;
  url: '/1/shares/code/{shareCodeId}';
};

export type SharesLinkShareCodeErrors = {
  /**
   * You cannot link your own shocker code / You already have this shocker linked to your account
   */
  400: OpenShockProblem;
  /**
   * Share code not found or does not belong to you
   */
  404: OpenShockProblem;
  /**
   * Error while linking share code to your account
   */
  500: unknown;
};

export type SharesLinkShareCodeError = SharesLinkShareCodeErrors[keyof SharesLinkShareCodeErrors];

export type SharesLinkShareCodeResponses = {
  /**
   * Linked share code
   */
  200: LegacyEmptyResponse;
};

export type SharesLinkShareCodeResponse =
  SharesLinkShareCodeResponses[keyof SharesLinkShareCodeResponses];

export type ShareLinksRemoveShockerData = {
  body?: never;
  path: {
    /**
     * Remove a shocker from a public share
     */
    publicShareId: string;
    /**
     * Remove a shocker from a public share
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shares/links/{publicShareId}/{shockerId}';
};

export type ShareLinksRemoveShockerErrors = {
  /**
   * Shocker does not exist in public share
   */
  400: unknown;
  /**
   * Public share or shocker does not exist
   */
  404: OpenShockProblem;
};

export type ShareLinksRemoveShockerError =
  ShareLinksRemoveShockerErrors[keyof ShareLinksRemoveShockerErrors];

export type ShareLinksRemoveShockerResponses = {
  /**
   * Successfully removed shocker
   */
  200: LegacyEmptyResponse;
};

export type ShareLinksRemoveShockerResponse =
  ShareLinksRemoveShockerResponses[keyof ShareLinksRemoveShockerResponses];

export type ShareLinksEditShockerData = {
  body: PublicShareEditShocker;
  path: {
    /**
     * Edit a shocker in a public share
     */
    publicShareId: string;
    /**
     * Edit a shocker in a public share
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shares/links/{publicShareId}/{shockerId}';
};

export type ShareLinksEditShockerErrors = {
  /**
   * Shocker does not exist in public share
   */
  400: unknown;
  /**
   * Public share or shocker does not exist
   */
  404: OpenShockProblem;
};

export type ShareLinksEditShockerError =
  ShareLinksEditShockerErrors[keyof ShareLinksEditShockerErrors];

export type ShareLinksEditShockerResponses = {
  /**
   * Successfully updated shocker
   */
  200: string;
};

export type ShareLinksEditShockerResponse =
  ShareLinksEditShockerResponses[keyof ShareLinksEditShockerResponses];

export type ShareLinksAddShockerData = {
  body?: never;
  path: {
    /**
     * Add a shocker to a public share
     */
    publicShareId: string;
    /**
     * Add a shocker to a public share
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shares/links/{publicShareId}/{shockerId}';
};

export type ShareLinksAddShockerErrors = {
  /**
   * Public share or shocker does not exist
   */
  404: OpenShockProblem;
  /**
   * Shocker already exists in public share
   */
  409: OpenShockProblem;
};

export type ShareLinksAddShockerError =
  ShareLinksAddShockerErrors[keyof ShareLinksAddShockerErrors];

export type ShareLinksAddShockerResponses = {
  /**
   * Successfully added shocker
   */
  200: LegacyEmptyResponse;
};

export type ShareLinksAddShockerResponse =
  ShareLinksAddShockerResponses[keyof ShareLinksAddShockerResponses];

export type ShareLinksListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/shares/links';
};

export type ShareLinksListResponses = {
  /**
   * All public shares for the current user
   */
  200: LegacyDataResponseOfArrayOfOwnPublicShareResponse;
};

export type ShareLinksListResponse = ShareLinksListResponses[keyof ShareLinksListResponses];

export type ShareLinksCreatePublicShareData = {
  body: PublicShareCreate;
  path?: never;
  query?: never;
  url: '/1/shares/links';
};

export type ShareLinksCreatePublicShareResponses = {
  /**
   * The created public share
   */
  200: LegacyDataResponseOfGuid;
};

export type ShareLinksCreatePublicShareResponse =
  ShareLinksCreatePublicShareResponses[keyof ShareLinksCreatePublicShareResponses];

export type ShareLinksDeletePublicShareData = {
  body?: never;
  path: {
    /**
     * Deletes a public share
     */
    publicShareId: string;
  };
  query?: never;
  url: '/1/shares/links/{publicShareId}';
};

export type ShareLinksDeletePublicShareErrors = {
  /**
   * Public share not found or does not belong to you
   */
  404: OpenShockProblem;
};

export type ShareLinksDeletePublicShareError =
  ShareLinksDeletePublicShareErrors[keyof ShareLinksDeletePublicShareErrors];

export type ShareLinksDeletePublicShareResponses = {
  /**
   * Deleted public share
   */
  200: LegacyEmptyResponse;
};

export type ShareLinksDeletePublicShareResponse =
  ShareLinksDeletePublicShareResponses[keyof ShareLinksDeletePublicShareResponses];

export type ShareLinksPauseShockerData = {
  body: PauseRequest;
  path: {
    /**
     * Pause a shocker in a public share
     */
    publicShareId: string;
    /**
     * Pause a shocker in a public share
     */
    shockerId: string;
  };
  query?: never;
  url: '/1/shares/links/{publicShareId}/{shockerId}/pause';
};

export type ShareLinksPauseShockerErrors = {
  /**
   * Shocker does not exist in public share
   */
  400: unknown;
  /**
   * Public share or shocker does not exist
   */
  404: OpenShockProblem;
};

export type ShareLinksPauseShockerError =
  ShareLinksPauseShockerErrors[keyof ShareLinksPauseShockerErrors];

export type ShareLinksPauseShockerResponses = {
  /**
   * Successfully updated paused state shocker
   */
  200: LegacyDataResponseOfPauseReason;
};

export type ShareLinksPauseShockerResponse =
  ShareLinksPauseShockerResponses[keyof ShareLinksPauseShockerResponses];

export type SessionsDeleteSessionData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: '/1/sessions/{sessionId}';
};

export type SessionsDeleteSessionErrors = {
  /**
   * Not Found
   */
  404: OpenShockProblem;
};

export type SessionsDeleteSessionError =
  SessionsDeleteSessionErrors[keyof SessionsDeleteSessionErrors];

export type SessionsDeleteSessionResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type SessionsListSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/sessions';
};

export type SessionsListSessionsResponses = {
  /**
   * OK
   */
  200: Array<LoginSessionResponse>;
};

export type SessionsListSessionsResponse =
  SessionsListSessionsResponses[keyof SessionsListSessionsResponses];

export type SessionsGetSelfSessionData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/sessions/self';
};

export type SessionsGetSelfSessionResponses = {
  /**
   * OK
   */
  200: LoginSessionResponse;
};

export type SessionsGetSelfSessionResponse =
  SessionsGetSelfSessionResponses[keyof SessionsGetSelfSessionResponses];

export type PublicGetOnlineDevicesStatisticsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/public/stats';
};

export type PublicGetOnlineDevicesStatisticsResponses = {
  /**
   * The statistics were successfully retrieved.
   */
  200: LegacyDataResponseOfStatsResponse;
};

export type PublicGetOnlineDevicesStatisticsResponse =
  PublicGetOnlineDevicesStatisticsResponses[keyof PublicGetOnlineDevicesStatisticsResponses];

export type PublicGetPublicShareData = {
  body?: never;
  path: {
    /**
     * Gets information about a public share.
     */
    publicShareId: string;
  };
  query?: never;
  url: '/1/public/shares/links/{publicShareId}';
};

export type PublicGetPublicShareErrors = {
  /**
   * The public share does not exist.
   */
  404: OpenShockProblem;
};

export type PublicGetPublicShareError =
  PublicGetPublicShareErrors[keyof PublicGetPublicShareErrors];

export type PublicGetPublicShareResponses = {
  /**
   * The public share information was successfully retrieved.
   */
  200: LegacyDataResponseOfPublicShareResponse;
};

export type PublicGetPublicShareResponse =
  PublicGetPublicShareResponses[keyof PublicGetPublicShareResponses];

export type DevicesOtaGetOtaUpdateHistoryData = {
  body?: never;
  path: {
    /**
     * Id of the device
     */
    deviceId: string;
  };
  query?: never;
  url: '/1/devices/{deviceId}/ota';
};

export type DevicesOtaGetOtaUpdateHistoryErrors = {
  /**
   * Could not find device or you do not have access to it
   */
  404: OpenShockProblem;
};

export type DevicesOtaGetOtaUpdateHistoryError =
  DevicesOtaGetOtaUpdateHistoryErrors[keyof DevicesOtaGetOtaUpdateHistoryErrors];

export type DevicesOtaGetOtaUpdateHistoryResponses = {
  /**
   * OK
   */
  200: LegacyDataResponseOfIReadOnlyCollectionOfOtaItem;
};

export type DevicesOtaGetOtaUpdateHistoryResponse =
  DevicesOtaGetOtaUpdateHistoryResponses[keyof DevicesOtaGetOtaUpdateHistoryResponses];

export type DevicesListDevicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/devices';
};

export type DevicesListDevicesResponses = {
  /**
   * All devices for the current user
   */
  200: LegacyDataResponseOfArrayOfDeviceResponse;
};

export type DevicesListDevicesResponse =
  DevicesListDevicesResponses[keyof DevicesListDevicesResponses];

export type DevicesCreateDeviceData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/devices';
};

export type DevicesCreateDeviceResponses = {
  /**
   * Successfully created device
   */
  201: string;
};

export type DevicesCreateDeviceResponse =
  DevicesCreateDeviceResponses[keyof DevicesCreateDeviceResponses];

export type DevicesRemoveDeviceData = {
  body?: never;
  path: {
    /**
     * The id of the device to delete
     */
    deviceId: string;
  };
  query?: never;
  url: '/1/devices/{deviceId}';
};

export type DevicesRemoveDeviceErrors = {
  /**
   * Device does not exist
   */
  404: OpenShockProblem;
};

export type DevicesRemoveDeviceError = DevicesRemoveDeviceErrors[keyof DevicesRemoveDeviceErrors];

export type DevicesRemoveDeviceResponses = {
  /**
   * Successfully deleted device
   */
  200: unknown;
};

export type DevicesGetDeviceByIdData = {
  body?: never;
  path: {
    /**
     * Get a device by its id
     */
    deviceId: string;
  };
  query?: never;
  url: '/1/devices/{deviceId}';
};

export type DevicesGetDeviceByIdErrors = {
  /**
   * Not Found
   */
  404: OpenShockProblem;
};

export type DevicesGetDeviceByIdError =
  DevicesGetDeviceByIdErrors[keyof DevicesGetDeviceByIdErrors];

export type DevicesGetDeviceByIdResponses = {
  /**
   * The device
   */
  200: LegacyDataResponseOfDeviceWithTokenResponse;
};

export type DevicesGetDeviceByIdResponse =
  DevicesGetDeviceByIdResponses[keyof DevicesGetDeviceByIdResponses];

export type DevicesEditDeviceData = {
  body: HubEditRequest;
  path: {
    /**
     * Edit a device
     */
    deviceId: string;
  };
  query?: never;
  url: '/1/devices/{deviceId}';
};

export type DevicesEditDeviceErrors = {
  /**
   * Device does not exist
   */
  404: OpenShockProblem;
};

export type DevicesEditDeviceError = DevicesEditDeviceErrors[keyof DevicesEditDeviceErrors];

export type DevicesEditDeviceResponses = {
  /**
   * Successfully updated device
   */
  200: unknown;
};

export type DevicesRegenerateDeviceTokenData = {
  body?: never;
  path: {
    /**
     * The id of the device to regenerate the token for
     */
    deviceId: string;
  };
  query?: never;
  url: '/1/devices/{deviceId}';
};

export type DevicesRegenerateDeviceTokenErrors = {
  /**
   * Device does not exist
   */
  404: OpenShockProblem;
  /**
   * Failed to save regenerated token
   */
  500: unknown;
};

export type DevicesRegenerateDeviceTokenError =
  DevicesRegenerateDeviceTokenErrors[keyof DevicesRegenerateDeviceTokenErrors];

export type DevicesRegenerateDeviceTokenResponses = {
  /**
   * Successfully regenerated device token
   */
  200: string;
};

export type DevicesRegenerateDeviceTokenResponse =
  DevicesRegenerateDeviceTokenResponses[keyof DevicesRegenerateDeviceTokenResponses];

export type DevicesGetPairCodeData = {
  body?: never;
  path: {
    /**
     * Get a pair code for a device
     */
    deviceId: string;
  };
  query?: never;
  url: '/1/devices/{deviceId}/pair';
};

export type DevicesGetPairCodeErrors = {
  /**
   * Device does not exist or does not belong to you
   */
  404: OpenShockProblem;
};

export type DevicesGetPairCodeError = DevicesGetPairCodeErrors[keyof DevicesGetPairCodeErrors];

export type DevicesGetPairCodeResponses = {
  /**
   * The pair code
   */
  200: LegacyDataResponseOfstring;
};

export type DevicesGetPairCodeResponse =
  DevicesGetPairCodeResponses[keyof DevicesGetPairCodeResponses];

export type DevicesGetLiveControlGatewayInfoData = {
  body?: never;
  path: {
    /**
     * Get LCG info for a device if it is online and connected to a LCG node
     */
    deviceId: string;
  };
  query?: never;
  url: '/1/devices/{deviceId}/lcg';
};

export type DevicesGetLiveControlGatewayInfoErrors = {
  /**
   * Device does not exist or does not belong to you
   */
  404: OpenShockProblem;
};

export type DevicesGetLiveControlGatewayInfoError =
  DevicesGetLiveControlGatewayInfoErrors[keyof DevicesGetLiveControlGatewayInfoErrors];

export type DevicesGetLiveControlGatewayInfoResponses = {
  /**
   * LCG node was found and device is online
   */
  200: LegacyDataResponseOfLcgResponse;
};

export type DevicesGetLiveControlGatewayInfoResponse =
  DevicesGetLiveControlGatewayInfoResponses[keyof DevicesGetLiveControlGatewayInfoResponses];

export type DevicesGetShockersData = {
  body?: never;
  path: {
    /**
     * The device id
     */
    deviceId: string;
  };
  query?: never;
  url: '/1/devices/{deviceId}/shockers';
};

export type DevicesGetShockersErrors = {
  /**
   * Device does not exists or you do not have access to it.
   */
  404: OpenShockProblem;
};

export type DevicesGetShockersError = DevicesGetShockersErrors[keyof DevicesGetShockersErrors];

export type DevicesGetShockersResponses = {
  /**
   * All shockers for the device
   */
  200: LegacyDataResponseOfArrayOfShockerResponse;
};

export type DevicesGetShockersResponse =
  DevicesGetShockersResponses[keyof DevicesGetShockersResponses];

export type DeviceGetLiveControlGatewayData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/device/assignLCG';
};

export type DeviceGetLiveControlGatewayErrors = {
  /**
   * Unable to find suitable LCG node
   */
  503: OpenShockProblem;
};

export type DeviceGetLiveControlGatewayError =
  DeviceGetLiveControlGatewayErrors[keyof DeviceGetLiveControlGatewayErrors];

export type DeviceGetLiveControlGatewayResponses = {
  /**
   * Successfully assigned LCG node
   */
  200: LegacyDataResponseOfLcgNodeResponse;
};

export type DeviceGetLiveControlGatewayResponse =
  DeviceGetLiveControlGatewayResponses[keyof DeviceGetLiveControlGatewayResponses];

export type DeviceGetSelfData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/device/self';
};

export type DeviceGetSelfResponses = {
  /**
   * The device information was successfully retrieved.
   */
  200: LegacyDataResponseOfDeviceSelfResponse;
};

export type DeviceGetSelfResponse = DeviceGetSelfResponses[keyof DeviceGetSelfResponses];

export type DevicePairData = {
  body?: never;
  path: {
    /**
     * The pair code to pair with.
     */
    pairCode: string;
  };
  query?: never;
  url: '/1/device/pair/{pairCode}';
};

export type DevicePairErrors = {
  /**
   * No such pair code exists
   */
  404: OpenShockProblem;
};

export type DevicePairError = DevicePairErrors[keyof DevicePairErrors];

export type DevicePairResponses = {
  /**
   * Successfully assigned LCG node
   */
  200: LegacyDataResponseOfstring;
};

export type DevicePairResponse = DevicePairResponses[keyof DevicePairResponses];

export type AdminListAutomationTokensData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/admin/automationTokens';
};

export type AdminListAutomationTokensResponses = {
  /**
   * OK
   */
  200: Array<AutomationTokenDto>;
};

export type AdminListAutomationTokensResponse =
  AdminListAutomationTokensResponses[keyof AdminListAutomationTokensResponses];

export type AdminCreateAutomationTokenData = {
  body: CreateAutomationTokenDto;
  path?: never;
  query?: never;
  url: '/1/admin/automationTokens';
};

export type AdminCreateAutomationTokenResponses = {
  /**
   * OK
   */
  200: CreatedAutomationTokenDto;
};

export type AdminCreateAutomationTokenResponse =
  AdminCreateAutomationTokenResponses[keyof AdminCreateAutomationTokenResponses];

export type AdminDeleteAutomationTokenData = {
  body?: never;
  path: {
    /**
     * Deletes an automation token together with every account it created. Refused while any of those
     * accounts holds a privileged role
     */
    id: string;
  };
  query?: never;
  url: '/1/admin/automationTokens/{id}';
};

export type AdminDeleteAutomationTokenErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
};

export type AdminDeleteAutomationTokenError =
  AdminDeleteAutomationTokenErrors[keyof AdminDeleteAutomationTokenErrors];

export type AdminDeleteAutomationTokenResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminPatchAutomationTokenData = {
  body: PatchAutomationTokenDto;
  path: {
    /**
     * Updates an automation token
     */
    id: string;
  };
  query?: never;
  url: '/1/admin/automationTokens/{id}';
};

export type AdminPatchAutomationTokenErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type AdminPatchAutomationTokenError =
  AdminPatchAutomationTokenErrors[keyof AdminPatchAutomationTokenErrors];

export type AdminPatchAutomationTokenResponses = {
  /**
   * OK
   */
  200: AutomationTokenDto;
};

export type AdminPatchAutomationTokenResponse =
  AdminPatchAutomationTokenResponses[keyof AdminPatchAutomationTokenResponses];

export type AdminRotateAutomationTokenData = {
  body?: never;
  path: {
    /**
     * Rotates the secret of an automation token. The new secret is only returned once, in this response
     */
    id: string;
  };
  query?: never;
  url: '/1/admin/automationTokens/{id}/rotate';
};

export type AdminRotateAutomationTokenErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type AdminRotateAutomationTokenError =
  AdminRotateAutomationTokenErrors[keyof AdminRotateAutomationTokenErrors];

export type AdminRotateAutomationTokenResponses = {
  /**
   * OK
   */
  200: CreatedAutomationTokenDto;
};

export type AdminRotateAutomationTokenResponse =
  AdminRotateAutomationTokenResponses[keyof AdminRotateAutomationTokenResponses];

export type AdminConfigurationListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/admin/config';
};

export type AdminConfigurationListErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminConfigurationListResponses = {
  /**
   * OK
   */
  200: Array<ConfigurationItemDto>;
};

export type AdminConfigurationListResponse =
  AdminConfigurationListResponses[keyof AdminConfigurationListResponses];

export type AdminConfigurationAddData = {
  body: ConfigurationAddItemRequest;
  path?: never;
  query?: never;
  url: '/1/admin/config';
};

export type AdminConfigurationAddErrors = {
  /**
   * Invalid name or value format
   */
  400: OpenShockProblem;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Already exists
   */
  409: OpenShockProblem;
};

export type AdminConfigurationAddError =
  AdminConfigurationAddErrors[keyof AdminConfigurationAddErrors];

export type AdminConfigurationAddResponses = {
  /**
   * Configuration added
   */
  200: unknown;
};

export type AdminConfigurationUpdateData = {
  body: ConfigurationUpdateItemRequest;
  path?: never;
  query?: never;
  url: '/1/admin/config';
};

export type AdminConfigurationUpdateErrors = {
  /**
   * Invalid name or value format or type mismatch
   */
  400: OpenShockProblem;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not found
   */
  404: OpenShockProblem;
  /**
   * Conflict
   */
  409: OpenShockProblem;
};

export type AdminConfigurationUpdateError =
  AdminConfigurationUpdateErrors[keyof AdminConfigurationUpdateErrors];

export type AdminConfigurationUpdateResponses = {
  /**
   * Configuration updated (or nothing to do)
   */
  200: unknown;
};

export type AdminConfigurationDeleteData = {
  body?: never;
  path: {
    /**
     * Deletes a configuration
     */
    name: string;
  };
  query?: never;
  url: '/1/admin/config/{name}';
};

export type AdminConfigurationDeleteErrors = {
  /**
   * Invalid name format
   */
  400: OpenShockProblem;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not found
   */
  404: OpenShockProblem;
};

export type AdminConfigurationDeleteError =
  AdminConfigurationDeleteErrors[keyof AdminConfigurationDeleteErrors];

export type AdminConfigurationDeleteResponses = {
  /**
   * Configuration deleted
   */
  200: unknown;
};

export type AdminDeactivateUserData = {
  body?: never;
  path: {
    /**
     * Deactivates a user
     */
    userId: string;
  };
  query?: {
    /**
     * Deactivates a user
     */
    deleteLater?: boolean;
    /**
     * Deactivates a user
     */
    reason?: string;
  };
  url: '/1/admin/users/{userId}/deactivate';
};

export type AdminDeactivateUserErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminDeactivateUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminDeleteApiTokenData = {
  body?: never;
  path: {
    /**
     * Deletes an API token
     */
    tokenId: string;
  };
  query?: never;
  url: '/1/admin/apitokens/{tokenId}';
};

export type AdminDeleteApiTokenErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminDeleteApiTokenResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminDeleteUserData = {
  body?: never;
  path: {
    /**
     * Deletes a user
     */
    userId: string;
  };
  query?: {
    /**
     * Deletes a user
     */
    reason?: string;
  };
  url: '/1/admin/users/{userId}';
};

export type AdminDeleteUserErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminDeleteUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminGetUserByIdData = {
  body?: never;
  path: {
    /**
     * Gets a user by id
     */
    userId: string;
  };
  query?: never;
  url: '/1/admin/users/{userId}';
};

export type AdminGetUserByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not found
   */
  404: ProblemDetails;
};

export type AdminGetUserByIdError = AdminGetUserByIdErrors[keyof AdminGetUserByIdErrors];

export type AdminGetUserByIdResponses = {
  /**
   * User info
   */
  200: AdminUserView;
};

export type AdminGetUserByIdResponse = AdminGetUserByIdResponses[keyof AdminGetUserByIdResponses];

export type AdminModifyUserData = {
  body: UserPatchDto;
  path: {
    /**
     * Edits a user
     */
    userId: string;
  };
  query?: never;
  url: '/1/admin/users/{userId}';
};

export type AdminModifyUserErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not found
   */
  404: unknown;
};

export type AdminModifyUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminBulkRequeueEmailOutboxData = {
  body: EmailOutboxBulkRequest;
  path?: never;
  query?: never;
  url: '/1/admin/email/outbox/bulk/requeue';
};

export type AdminBulkRequeueEmailOutboxErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminBulkRequeueEmailOutboxResponses = {
  /**
   * Bulk requeue applied
   */
  200: EmailOutboxBulkResultDto;
};

export type AdminBulkRequeueEmailOutboxResponse =
  AdminBulkRequeueEmailOutboxResponses[keyof AdminBulkRequeueEmailOutboxResponses];

export type AdminBulkCancelEmailOutboxData = {
  body: EmailOutboxBulkRequest;
  path?: never;
  query?: never;
  url: '/1/admin/email/outbox/bulk/cancel';
};

export type AdminBulkCancelEmailOutboxErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminBulkCancelEmailOutboxResponses = {
  /**
   * Bulk cancel applied
   */
  200: EmailOutboxBulkResultDto;
};

export type AdminBulkCancelEmailOutboxResponse =
  AdminBulkCancelEmailOutboxResponses[keyof AdminBulkCancelEmailOutboxResponses];

export type AdminBulkDeleteEmailOutboxData = {
  body: EmailOutboxBulkRequest;
  path?: never;
  query?: never;
  url: '/1/admin/email/outbox/bulk/delete';
};

export type AdminBulkDeleteEmailOutboxErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminBulkDeleteEmailOutboxResponses = {
  /**
   * Bulk delete applied
   */
  200: EmailOutboxBulkResultDto;
};

export type AdminBulkDeleteEmailOutboxResponse =
  AdminBulkDeleteEmailOutboxResponses[keyof AdminBulkDeleteEmailOutboxResponses];

export type AdminCancelEmailOutboxData = {
  body?: never;
  path: {
    /**
     * Cancels a still-pending email outbox message by marking it skipped, so it is never sent. Only
     * pending messages can be cancelled; a message already being sent or in a terminal state cannot.
     */
    id: string;
  };
  query?: never;
  url: '/1/admin/email/outbox/{id}/cancel';
};

export type AdminCancelEmailOutboxErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * No such message
   */
  404: ProblemDetails;
  /**
   * Message is not pending
   */
  409: ProblemDetails;
};

export type AdminCancelEmailOutboxError =
  AdminCancelEmailOutboxErrors[keyof AdminCancelEmailOutboxErrors];

export type AdminCancelEmailOutboxResponses = {
  /**
   * Cancelled
   */
  200: unknown;
};

export type AdminDeleteEmailOutboxData = {
  body?: never;
  path: {
    /**
     * Permanently deletes an email outbox message. If the delivery consumer is mid-send it simply finds
     * the row gone and does nothing, so a delete never corrupts an in-flight send.
     */
    id: string;
  };
  query?: never;
  url: '/1/admin/email/outbox/{id}';
};

export type AdminDeleteEmailOutboxErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * No such message
   */
  404: ProblemDetails;
};

export type AdminDeleteEmailOutboxError =
  AdminDeleteEmailOutboxErrors[keyof AdminDeleteEmailOutboxErrors];

export type AdminDeleteEmailOutboxResponses = {
  /**
   * Deleted
   */
  200: unknown;
};

export type AdminGetEmailOutboxData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Lists email outbox messages, paginated. Supports the same OData-style
     * `$filter`/`$orderby` as the users listing (e.g. `status eq 'failed'`,
     * `recipient ilike '%@example.com'`). Defaults to newest first.
     */
    $filter?: string;
    /**
     * Lists email outbox messages, paginated. Supports the same OData-style
     * `$filter`/`$orderby` as the users listing (e.g. `status eq 'failed'`,
     * `recipient ilike '%@example.com'`). Defaults to newest first.
     */
    $orderby?: string;
    /**
     * Lists email outbox messages, paginated. Supports the same OData-style
     * `$filter`/`$orderby` as the users listing (e.g. `status eq 'failed'`,
     * `recipient ilike '%@example.com'`). Defaults to newest first.
     */
    $offset?: number;
    /**
     * Lists email outbox messages, paginated. Supports the same OData-style
     * `$filter`/`$orderby` as the users listing (e.g. `status eq 'failed'`,
     * `recipient ilike '%@example.com'`). Defaults to newest first.
     */
    $limit?: number;
  };
  url: '/1/admin/email/outbox';
};

export type AdminGetEmailOutboxErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminGetEmailOutboxResponses = {
  /**
   * Paginated email outbox messages
   */
  200: PaginatedOfEmailOutboxMessageDto;
};

export type AdminGetEmailOutboxResponse =
  AdminGetEmailOutboxResponses[keyof AdminGetEmailOutboxResponses];

export type AdminRequeueEmailOutboxData = {
  body?: never;
  path: {
    /**
     * Requeues a terminal (sent/failed/skipped) email outbox message: resets it to pending, due now,
     * with a fresh attempt budget, and nudges the delivery consumer to send it immediately.
     */
    id: string;
  };
  query?: never;
  url: '/1/admin/email/outbox/{id}/requeue';
};

export type AdminRequeueEmailOutboxErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * No such message
   */
  404: ProblemDetails;
  /**
   * Message is pending or currently being sent
   */
  409: ProblemDetails;
};

export type AdminRequeueEmailOutboxError =
  AdminRequeueEmailOutboxErrors[keyof AdminRequeueEmailOutboxErrors];

export type AdminRequeueEmailOutboxResponses = {
  /**
   * Requeued
   */
  200: unknown;
};

export type AdminGetEmailOutboxStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/admin/email/outbox/stats';
};

export type AdminGetEmailOutboxStatsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminGetEmailOutboxStatsResponses = {
  /**
   * Per-status counts
   */
  200: EmailOutboxStatsDto;
};

export type AdminGetEmailOutboxStatsResponse =
  AdminGetEmailOutboxStatsResponses[keyof AdminGetEmailOutboxStatsResponses];

export type AdminSendTestEmailData = {
  body: SendTestEmailDto;
  path?: never;
  query?: never;
  url: '/1/admin/email/test';
};

export type AdminSendTestEmailErrors = {
  /**
   * Invalid recipient address
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminSendTestEmailError = AdminSendTestEmailErrors[keyof AdminSendTestEmailErrors];

export type AdminSendTestEmailResponses = {
  /**
   * Test email enqueued
   */
  200: EmailOutboxMessageDto;
};

export type AdminSendTestEmailResponse =
  AdminSendTestEmailResponses[keyof AdminSendTestEmailResponses];

export type AdminListEmailProviderBlacklistData = {
  body?: never;
  path?: never;
  query?: {
    match?: string;
  };
  url: '/1/admin/blacklist/emailProviders';
};

export type AdminListEmailProviderBlacklistResponses = {
  /**
   * OK
   */
  200: Array<EmailProviderBlacklistDto>;
};

export type AdminListEmailProviderBlacklistResponse =
  AdminListEmailProviderBlacklistResponses[keyof AdminListEmailProviderBlacklistResponses];

export type AdminAddEmailProviderBlacklistData = {
  body: AddEmailProviderBlacklistDto;
  path?: never;
  query?: never;
  url: '/1/admin/blacklist/emailProviders';
};

export type AdminAddEmailProviderBlacklistResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminRemoveEmailProviderBlacklistData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/1/admin/blacklist/emailProviders/{id}';
};

export type AdminRemoveEmailProviderBlacklistErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type AdminRemoveEmailProviderBlacklistError =
  AdminRemoveEmailProviderBlacklistErrors[keyof AdminRemoveEmailProviderBlacklistErrors];

export type AdminRemoveEmailProviderBlacklistResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminGetAdminAuditLogData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page, sort, and search parameters.
     */
    page?: number;
    /**
     * Page, sort, and search parameters.
     */
    pageSize?: number;
    /**
     * Page, sort, and search parameters.
     */
    search?: string;
    /**
     * Page, sort, and search parameters.
     */
    sort?: string;
    /**
     * Page, sort, and search parameters.
     */
    sortDir?: SortDirection;
    /**
     * Optional: filter by the subject user (the account that was affected).
     */
    userId?: string;
    /**
     * Optional: filter by the actor (who performed the action).
     */
    actorId?: string;
  };
  url: '/1/admin/audit-log';
};

export type AdminGetAdminAuditLogResponses = {
  /**
   * A page of audit log entries.
   */
  200: PagedResultOfAuditLogEntryResponse;
};

export type AdminGetAdminAuditLogResponse =
  AdminGetAdminAuditLogResponses[keyof AdminGetAdminAuditLogResponses];

export type AdminGetOnlineDevicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/admin/monitoring/onlineDevices';
};

export type AdminGetOnlineDevicesErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminGetOnlineDevicesResponses = {
  /**
   * All online devices
   */
  200: LegacyDataResponseOfArrayOfAdminOnlineDeviceResponse;
};

export type AdminGetOnlineDevicesResponse =
  AdminGetOnlineDevicesResponses[keyof AdminGetOnlineDevicesResponses];

export type AdminGetOnlineGatewaysData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/admin/monitoring/gateways';
};

export type AdminGetOnlineGatewaysErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminGetOnlineGatewaysResponses = {
  /**
   * All online gateways
   */
  200: Array<AdminOnlineGatewayResponse>;
};

export type AdminGetOnlineGatewaysResponse =
  AdminGetOnlineGatewaysResponses[keyof AdminGetOnlineGatewaysResponses];

export type AdminGetUsersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Gets all users, paginated
     */
    $filter?: string;
    /**
     * Gets all users, paginated
     */
    $orderby?: string;
    /**
     * Gets all users, paginated
     */
    $offset?: number;
    /**
     * Gets all users, paginated
     */
    $limit?: number;
  };
  url: '/1/admin/users';
};

export type AdminGetUsersErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminGetUsersResponses = {
  /**
   * Paginated users
   */
  200: PaginatedOfAdminUsersView;
};

export type AdminGetUsersResponse = AdminGetUsersResponses[keyof AdminGetUsersResponses];

export type AdminReactivateUserData = {
  body?: never;
  path: {
    /**
     * Reactivates a user
     */
    userId: string;
  };
  query?: {
    /**
     * Reactivates a user
     */
    reason?: string;
  };
  url: '/1/admin/users/{userId}/reactivate';
};

export type AdminReactivateUserErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminReactivateUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminSetUserEmailData = {
  body: SetUserEmailRequestBody;
  path: {
    userId: string;
  };
  query?: never;
  url: '/1/admin/users/{userId}/email';
};

export type AdminSetUserEmailErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not found
   */
  404: ProblemDetails;
};

export type AdminSetUserEmailError = AdminSetUserEmailErrors[keyof AdminSetUserEmailErrors];

export type AdminSetUserEmailResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminSetUserNameData = {
  body: SetUserNameRequestBody;
  path: {
    userId: string;
  };
  query?: never;
  url: '/1/admin/users/{userId}/name';
};

export type AdminSetUserNameErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not found
   */
  404: ProblemDetails;
  /**
   * The target account is deactivated or not yet activated
   */
  409: OpenShockProblem;
};

export type AdminSetUserNameError = AdminSetUserNameErrors[keyof AdminSetUserNameErrors];

export type AdminSetUserNameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminSetUserPasswordData = {
  body: SetUserPasswordRequestBody;
  path: {
    userId: string;
  };
  query?: never;
  url: '/1/admin/users/{userId}/password';
};

export type AdminSetUserPasswordErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not found
   */
  404: ProblemDetails;
  /**
   * The target account is deactivated or not yet activated
   */
  409: OpenShockProblem;
};

export type AdminSetUserPasswordError =
  AdminSetUserPasswordErrors[keyof AdminSetUserPasswordErrors];

export type AdminSetUserPasswordResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminListUsernameBlacklistData = {
  body?: never;
  path?: never;
  query?: {
    match?: string;
  };
  url: '/1/admin/blacklist/usernames';
};

export type AdminListUsernameBlacklistResponses = {
  /**
   * OK
   */
  200: Array<UserNameBlacklistDto>;
};

export type AdminListUsernameBlacklistResponse =
  AdminListUsernameBlacklistResponses[keyof AdminListUsernameBlacklistResponses];

export type AdminAddUsernameBlacklistData = {
  body: AddUsernameBlacklistDto;
  path?: never;
  query?: never;
  url: '/1/admin/blacklist/usernames';
};

export type AdminAddUsernameBlacklistResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminRemoveUsernameBlacklistData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/1/admin/blacklist/usernames/{id}';
};

export type AdminRemoveUsernameBlacklistErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type AdminRemoveUsernameBlacklistError =
  AdminRemoveUsernameBlacklistErrors[keyof AdminRemoveUsernameBlacklistErrors];

export type AdminRemoveUsernameBlacklistResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminListWebhooksData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/admin/webhooks';
};

export type AdminListWebhooksErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminListWebhooksResponses = {
  /**
   * OK
   */
  200: Array<WebhookDto>;
};

export type AdminListWebhooksResponse =
  AdminListWebhooksResponses[keyof AdminListWebhooksResponses];

export type AdminAddWebhookData = {
  body: AddWebhookDto;
  path?: never;
  query?: never;
  url: '/1/admin/webhooks';
};

export type AdminAddWebhookErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
};

export type AdminAddWebhookError = AdminAddWebhookErrors[keyof AdminAddWebhookErrors];

export type AdminAddWebhookResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AdminRemoveWebhookData = {
  body?: never;
  path: {
    /**
     * Removes a webhook
     */
    id: string;
  };
  query?: never;
  url: '/1/admin/webhooks/{id}';
};

export type AdminRemoveWebhookErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type AdminRemoveWebhookError = AdminRemoveWebhookErrors[keyof AdminRemoveWebhookErrors];

export type AdminRemoveWebhookResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AccountActivateData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Activate account
     */
    token?: string;
  };
  url: '/1/account/activate';
};

export type AccountActivateErrors = {
  /**
   * Bad Request
   */
  400: OpenShockProblem;
};

export type AccountActivateError = AccountActivateErrors[keyof AccountActivateErrors];

export type AccountActivateResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AccountCheckUsernameData = {
  body: ChangeUsernameRequest;
  path?: never;
  query?: never;
  url: '/1/account/username/check';
};

export type AccountCheckUsernameResponses = {
  /**
   * OK
   */
  200: UsernameCheckResponse;
};

export type AccountCheckUsernameResponse =
  AccountCheckUsernameResponses[keyof AccountCheckUsernameResponses];

export type AccountLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/account/logout';
};

export type AccountLogoutResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AccountPasswordResetCheckValidData = {
  body?: never;
  path: {
    /**
     * The id of the password reset
     */
    passwordResetId: string;
    /**
     * The secret of the password reset
     */
    secret: string;
  };
  query?: never;
  url: '/1/account/password-reset/{passwordResetId}/{secret}';
};

export type AccountPasswordResetCheckValidErrors = {
  /**
   * Password reset process not found
   */
  404: OpenShockProblem;
};

export type AccountPasswordResetCheckValidError =
  AccountPasswordResetCheckValidErrors[keyof AccountPasswordResetCheckValidErrors];

export type AccountPasswordResetCheckValidResponses = {
  /**
   * Valid password reset process
   */
  200: LegacyEmptyResponse;
};

export type AccountPasswordResetCheckValidResponse =
  AccountPasswordResetCheckValidResponses[keyof AccountPasswordResetCheckValidResponses];

export type AccountPasswordResetCompleteData = {
  body: PasswordResetProcessData;
  path: {
    passwordResetId: string;
    secret: string;
  };
  query?: never;
  url: '/1/account/password-reset/{passwordResetId}/{secret}/complete';
};

export type AccountPasswordResetCompleteErrors = {
  /**
   * Password reset process not found
   */
  404: OpenShockProblem;
};

export type AccountPasswordResetCompleteError =
  AccountPasswordResetCompleteErrors[keyof AccountPasswordResetCompleteErrors];

export type AccountPasswordResetCompleteResponses = {
  /**
   * Password successfully changed
   */
  200: LegacyEmptyResponse;
};

export type AccountPasswordResetCompleteResponse =
  AccountPasswordResetCompleteResponses[keyof AccountPasswordResetCompleteResponses];

export type AccountEmailVerifyData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Verify a pending email change using the token from the verification email.
     */
    token?: string;
  };
  url: '/1/account/email-change/verify';
};

export type AccountEmailVerifyErrors = {
  /**
   * Token is invalid, already used, or the request has expired
   */
  400: OpenShockProblem;
  /**
   * The new email address was claimed by another account before verification completed
   */
  409: OpenShockProblem;
};

export type AccountEmailVerifyError = AccountEmailVerifyErrors[keyof AccountEmailVerifyErrors];

export type AccountEmailVerifyResponses = {
  /**
   * Email change verified and applied
   */
  200: unknown;
};

export type AccountEmailVerifyLegacyData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Verify a pending email change. Deprecated: use POST /email-change/verify instead.
     */
    token?: string;
  };
  url: '/1/account/verify-email';
};

export type AccountEmailVerifyLegacyErrors = {
  /**
   * Token is invalid, already used, or the request has expired
   */
  400: OpenShockProblem;
  /**
   * The new email address was claimed by another account before verification completed
   */
  409: OpenShockProblem;
};

export type AccountEmailVerifyLegacyError =
  AccountEmailVerifyLegacyErrors[keyof AccountEmailVerifyLegacyErrors];

export type AccountEmailVerifyLegacyResponses = {
  /**
   * Email change verified and applied
   */
  200: unknown;
};

export type AuthenticatedAccountChangeEmailData = {
  body: ChangeEmailRequest;
  path?: never;
  query?: never;
  url: '/1/account/email-change';
};

export type AuthenticatedAccountChangeEmailErrors = {
  /**
   * Bad Request
   */
  400: OpenShockProblem;
  /**
   * Unauthorized
   */
  401: OpenShockProblem;
  /**
   * Forbidden
   */
  403: OpenShockProblem;
  /**
   * Conflict
   */
  409: OpenShockProblem;
  /**
   * Too Many Requests
   */
  429: OpenShockProblem;
};

export type AuthenticatedAccountChangeEmailError =
  AuthenticatedAccountChangeEmailErrors[keyof AuthenticatedAccountChangeEmailErrors];

export type AuthenticatedAccountChangeEmailResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AuthenticatedAccountChangePasswordData = {
  body: ChangePasswordRequest;
  path?: never;
  query?: never;
  url: '/1/account/password';
};

export type AuthenticatedAccountChangePasswordErrors = {
  /**
   * Forbidden
   */
  403: OpenShockProblem;
  /**
   * Conflict
   */
  409: OpenShockProblem;
};

export type AuthenticatedAccountChangePasswordError =
  AuthenticatedAccountChangePasswordErrors[keyof AuthenticatedAccountChangePasswordErrors];

export type AuthenticatedAccountChangePasswordResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AuthenticatedAccountChangeUsernameData = {
  body: ChangeUsernameRequest;
  path?: never;
  query?: never;
  url: '/1/account/username';
};

export type AuthenticatedAccountChangeUsernameErrors = {
  /**
   * Bad Request
   */
  400: OpenShockProblem;
  /**
   * Forbidden
   */
  403: OpenShockProblem;
  /**
   * Conflict
   */
  409: OpenShockProblem;
};

export type AuthenticatedAccountChangeUsernameError =
  AuthenticatedAccountChangeUsernameErrors[keyof AuthenticatedAccountChangeUsernameErrors];

export type AuthenticatedAccountChangeUsernameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AuthenticatedAccountDeactivateData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/account';
};

export type AuthenticatedAccountDeactivateErrors = {
  /**
   * Forbidden
   */
  403: OpenShockProblem;
};

export type AuthenticatedAccountDeactivateError =
  AuthenticatedAccountDeactivateErrors[keyof AuthenticatedAccountDeactivateErrors];

export type AuthenticatedAccountDeactivateResponses = {
  /**
   * Done.
   */
  204: void;
};

export type AuthenticatedAccountDeactivateResponse =
  AuthenticatedAccountDeactivateResponses[keyof AuthenticatedAccountDeactivateResponses];

export type AuthenticatedAccountGetAuditLogData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page, sort, and search parameters.
     */
    page?: number;
    /**
     * Page, sort, and search parameters.
     */
    pageSize?: number;
    /**
     * Page, sort, and search parameters.
     */
    search?: string;
    /**
     * Page, sort, and search parameters.
     */
    sort?: string;
    /**
     * Page, sort, and search parameters.
     */
    sortDir?: SortDirection;
  };
  url: '/1/account/audit-log';
};

export type AuthenticatedAccountGetAuditLogResponses = {
  /**
   * A page of audit log entries.
   */
  200: PagedResultOfAuditLogEntryResponse;
};

export type AuthenticatedAccountGetAuditLogResponse =
  AuthenticatedAccountGetAuditLogResponses[keyof AuthenticatedAccountGetAuditLogResponses];

export type AuthenticatedAccountRemoveOAuthConnectionData = {
  body?: never;
  path: {
    /**
     * Provider key (e.g. `discord`).
     */
    provider: string;
  };
  query?: never;
  url: '/1/account/connections/{provider}';
};

export type AuthenticatedAccountRemoveOAuthConnectionErrors = {
  /**
   * No connection found for this provider.
   */
  404: ProblemDetails;
};

export type AuthenticatedAccountRemoveOAuthConnectionError =
  AuthenticatedAccountRemoveOAuthConnectionErrors[keyof AuthenticatedAccountRemoveOAuthConnectionErrors];

export type AuthenticatedAccountRemoveOAuthConnectionResponses = {
  /**
   * Connection removed.
   */
  204: void;
};

export type AuthenticatedAccountRemoveOAuthConnectionResponse =
  AuthenticatedAccountRemoveOAuthConnectionResponses[keyof AuthenticatedAccountRemoveOAuthConnectionResponses];

export type AuthenticatedAccountListOAuthConnectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/1/account/connections';
};

export type AuthenticatedAccountListOAuthConnectionsResponses = {
  /**
   * Returns the list of connections.
   */
  200: Array<OAuthConnectionResponse>;
};

export type AuthenticatedAccountListOAuthConnectionsResponse =
  AuthenticatedAccountListOAuthConnectionsResponses[keyof AuthenticatedAccountListOAuthConnectionsResponses];
