name: ci-lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  build-and-test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc

      - name: Install pnpm & dependencies
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          cache: true
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Run Formatting Check
        run: pnpm run format:check

      - name: Run Linting
        run: pnpm run lint
