on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, reopened, synchronize]
  workflow_dispatch: # Manually invoked by user.

name: ci-test

env:
  NODE_VERSION: 20

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build
        with:
          node-version: ${{ env.NODE_VERSION }}
          upload-artifact: false