name: Node CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Install playwright
        run: npx playwright install
      - name: Install playwright dependencies
        run: npx playwright install-deps
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Run svelte-check
        run: npm run check
      - name: Build app
        run: npm run build
